### ISSUE TITLE
How to change the src of script?

### ISSUE THREAD

**Issue by Candy-Box** [DethAriel/ng-recaptcha#101]
### Summary

I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [x] question / support request
- [ ] other

### Description

I want to use the recaptcha in china, so I want to change the https://www.google.com/recaptcha/api.js?render=explicit to https://recaptcha.net/recaptcha/api.js?render=explicit, so how to implement it?

**Comment by mildata** [comment]
Ran into the same issue. Is it possible to change src?

**Comment by CallMeGary** [comment]
Same here

**Comment by DethAriel** [comment]
@Candy-Box @mildata @CallMeGary  this is now available in `^4.2.0`, see [this section in README](https://github.com/DethAriel/ng-recaptcha#example-different-url)
