### ISSUE TITLE
Getting import errors after including ng-recaptcha

### ISSUE THREAD

**Issue by vivekkumar27june88** [DethAriel/ng-recaptcha#102]
I'm using ng-packgr for making angular lib. After using `ng-recaptcha`, the generated package give below error
```
 Uncaught TypeError: core_1.NgModule is not a function 
```

Following the step mentioned in the below and adding the below lines in ng-package.json , still getting this error
https://github.com/dherges/ng-packagr/issues/210

```lib": {
        "entryFile": "public_api.ts",
        "externals": {
            "@angular/material": "angular/material",
            "@angular/flex-layout": "angular/flex-layout",
            "@angular/animations": "@angular/animations",
            "@angular/cdk": "@angular/cdk",
            "@angular/common": "@angular/common",
            "@angular/compiler": "@angular/compiler",
            "@angular/core": "@angular/core",
            "@angular/forms": "@angular/forms",
            "@angular/http": "@angular/http",
            "@angular/platform-browser": "angular/platform-browser",
            "@angular/platform-browser-dynamic": "@angular/platform-browser-dynamic",
            "@angular/router": "@angular/router",
            "angular-auth-oidc-client": "angular-auth-oidc-client",
            "core-js": "core-js",
            "angular-hammer": "angular-hammer",
            "ng-recaptcha": "ng-recaptcha",
}
}
```
---
It seems the below imports are getting added by ng-recaptcha

```
import core_1 {Component, ....} from '@angular/core';
import form { FormModule} from '@angular/form';
```

Any idea why is happening?

**Comment by vivekkumar27june88** [comment]
Debugging further It seems that the `RecaptchFormsModule` is causing the problem.

**Comment by DethAriel** [comment]
Hi, @vivekkumar27june88 ! 

I'm not familiar with `ng-packgr`, but I will try to assist you. One of the most common problems with `RecaptchaFormsModule` in the past was the fact that it wasn't imported in your app. As seen in [Basic Usage](https://github.com/DethAriel/ng-recaptcha#example-basic), you will need to include it as well as the `RecaptchaModule`:

```ts
import { RecaptchaModule } from 'ng-recaptcha';
import { RecaptchaFormsModule } from 'ng-recaptcha/forms';
import { BrowserModule }  from '@angular/platform-browser';
import { MyApp } from './app.component.ts';

@NgModule({
  bootstrap: [MyApp],
  declarations: [MyApp],
  imports: [
    BrowserModule,
    RecaptchaModule.forRoot(), // Keep in mind the "forRoot"-magic nuances!
    RecaptchaFormsModule, // if you need forms support
  ],
})
export class MyAppModule { }
```

Please let me know if this helps, or provide more details on the issue so that I could assist you further

**Comment by vivekkumar27june88** [comment]
Thanks @DethAriel for the reply and I'm sorry for following up so late. 

I guess the problem I was getting at that point of time may be related with `ng-packagr`.

It would be nice if you please elaborate this line
>>> // Keep in mind the "forRoot"-magic nuances!


One more thing, What If I am creating an angular library and using `ng-recaptcha` in it. It's in not working in this case when generating the package.

**Comment by DethAriel** [comment]
@vivekkumar27june88 starting with `ng-recaptcha` version 4.1.0 you no longer need to call the `.forRoot()` function! I'm going to close this issue, cause it seems to be resolved now
