### ISSUE TITLE
Plunkr in README not working - 404

### ISSUE THREAD

**Issue by macbem** [DethAriel/ng-recaptcha#105]
This plunkr is not working anymore - https://plnkr.co/edit/JNVNl0WJl3bFuWtt2O9i?p=preview.

BTW, maybe it'd be nice use Stackblitz?

**Comment by DethAriel** [comment]
Thx for submitting this, @macbem !

I fixed the plunker for now - the problem consisted in the fact that plunk depended on `latest` Angular,  so the thing broke as soon as they release v6.

On a different note - Stackblitz looks great, and I would gladly accept a PR that will port example into there! I opened #109 to track that, and I'll close this issue in the meanwhile
