### ISSUE TITLE
How to load siteKey dynamically from some component variable..?

### ISSUE THREAD

**Issue by chintuboy** [DethAriel/ng-recaptcha#106]
```
<re-captcha formControlName="recaptcha" (resolved)="resolved($event)" siteKey="reCaptchakey"></re-captcha>
```
in HTML and

```
public reCaptchakey: string = <SITE_KEY>;
```
in ts file, but this is not working, so how to load site key value using variable..??

**Comment by vivekkurien** [comment]
The site key is an Input in reCaptcha component.
You can add the site key dynamically by changing  code as below

`<re-captcha formControlName="recaptcha" (resolved)="resolved($event)" [siteKey]="reCaptchakey"></re-captcha>`

**Comment by DethAriel** [comment]
@chintuboy the comment by @vivekkurien should've solved your issue, so I'm closing it. Feel free to re-open if you have any further problems
