### ISSUE TITLE
Angular 6, peer dependency warning

### ISSUE THREAD

**Issue by dauledk** [DethAriel/ng-recaptcha#108]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description
When using ng-recaptcha@3.0.5 I get the following warning on `npm i`:

`npm WARN ng-recaptcha@3.0.5 requires a peer of @angular/core@^4.0.0 || ^5.0.0-beta.1 but none is installed. You must install peer dependencies yourself.`

**Comment by DethAriel** [comment]
Hi, @dauledk !

Angular v6 support is now available as a beta in `ng-recaptcha@4.0.0-beta.1`
