### ISSUE TITLE
Enhance code examples

### ISSUE THREAD

**Issue by DethAriel** [DethAriel/ng-recaptcha#109]
### Summary

The code live in [plunker](https://plnkr.co/edit/JNVNl0WJl3bFuWtt2O9i?p=preview) at the moment. There are a lot of great things out there (like [Stackblitz](https://stackblitz.com/)), we should probably consider moving them!

**Comment by macbem** [comment]
Is [this](https://stackblitz.com/edit/ng-recaptcha-demo) good enough? If so, I'll send a PR to include it in the readme.

**Comment by DethAriel** [comment]
@macbem I believe this is good enough, yes 👍 

What I'm thinking, though, is that Stackblitz does not seem to provide the ability to have shared ownership, so if you put your example in the readme - I'll have to ping you every time I want it changed, which is non-ideal. 

I've [forked your example](https://stackblitz.com/edit/ng-recaptcha-example), hope you don't mind. Feel free to submit a PR!

**Comment by macbem** [comment]
Sure, that's a fair concern. I'll link the PR here in minutes.
