### ISSUE TITLE
Support RxJs 6 and Angular 6

### ISSUE THREAD

**Issue by micksatana** [DethAriel/ng-recaptcha#111]
### Summary

I'm submitting a: 
- [ ] bug report
- [x] feature request
- [ ] question / support request
- [ ] other

### Description
reCaptcha to support RxJs and Angular version 6

I try changing [these lines](https://github.com/DethAriel/ng-recaptcha/blob/bde1c635991a0590805a65c364e21b54a3317fc3/recaptcha/recaptcha-loader.service.ts#L9-L11) to
```
import { BehaviorSubject } from 'rxjs';
import { Observable } from 'rxjs';
import { of } from 'rxjs';
```
and update the dependencies.

### Demo

- [x] I did my best to come up with a [fork updated files related to rxjs](https://github.com/intocode-io/ng-recaptcha/tree/support-rxjs-6). It's not yet runnable though.

A_LINK_WITH_YOUR_EXAMPLE

Lib versions:

* ng-recaptcha: 3.0.5
* Angular: 6.0.2
* Typescript (`tsc --version`): 2.7.2

**Comment by DethAriel** [comment]
Hi, @micksatana! At the moment you can use either rxjs-compat module with v3.0.5 as seen [here](https://stackblitz.com/edit/ng-recaptcha-example), or install v4.0.0-beta.1 which has been refactored for Angular v6 support

**Comment by elessariel** [comment]
When using the beta 1 for Angular 6 I'm getting a

`ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[RecaptchaComponent -> RecaptchaLoaderService]: 
  StaticInjectorError(Platform: core)[RecaptchaComponent -> RecaptchaLoaderService]: 
    NullInjectorError: No provider for RecaptchaLoaderService!
Error: StaticInjectorError(AppModule)[RecaptchaComponent -> RecaptchaLoaderService]: 
  StaticInjectorError(Platform: core)[RecaptchaComponent -> RecaptchaLoaderService]: 
    NullInjectorError: No provider for RecaptchaLoaderService!
    at `

Anything I can do at this point ?

**Comment by Kiran-B** [comment]
Noticed a beta version is already out. Hope to see the release soon.

**Comment by Worthy7** [comment]
Are you going to release this @DethAriel ? It's been a few months

**Comment by DethAriel** [comment]
Folks, a stable 4.0.0 has been released now, so feel free to upgrade!
