### ISSUE TITLE
Can't publish dotnet angular app with ng-recaptcha - Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory'

### ISSUE THREAD

**Issue by tonmoypaul** [DethAriel/ng-recaptcha#112]
### Summary

I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [x] question / support request
- [ ] other

### Description

I get follwing error when trying to publish my dotnet angular app only when ng-recaptcha is installed. The ng-recaptcha works fine when I run the app in my local machine.

```
 Hash: 0e8fdf7b8b2bc0473506
      Time: 8448ms
               Asset    Size  Chunks                    Chunk Names
      main-client.js  268 kB       0  [emitted]  [big]  main-client

      ERROR in ./ClientApp/boot.browser.ts
Module not found : error : Can't resolve './../$$_gendir/ClientApp/app/app.browser.module.ngfactory' in 'C:\abc\JWT\JWT\ClientApp' [C:\abc\JWT\JWT\JWT.csproj]
       @ ./ClientApp/boot.browser.ts 5:0-95
  Child
      Hash: ad57238c08f01efa761b
      Time: 8578ms
               Asset     Size  Chunks                    Chunk Names
      main-server.js  1.81 MB       0  [emitted]  [big]  main-server

      ERROR in ./ClientApp/boot.server.ts
Module not found : error : Can't resolve './../$$_gendir/ClientApp/app/app.server.module.ngfactory' in 'C:\abc\JWT\JWT\ClientApp' [C:\abc\JWT\JWT\JWT.csproj]
       @ ./ClientApp/boot.server.ts 8:0-94
C:\abc\JWT\JWT\JWT.csproj(48,5): error MSB3073: The command "node node_modules/webpack/bin/webpack.js --env.prod" exited with code 2.
```
Can you please advise what could cause this or any known fix for this? Thanks

https://stackoverflow.com/questions/50469628/ng-recaptcha-publish-time-error-module-not-found-error-cant-resolve-g

Lib versions:
* ng-recaptcha: "^3.0.5"
* Angular: "4.2.5"
* Typescript (`tsc --version`): "2.6.1"

**Comment by DethAriel** [comment]
Hello @tonmoypaul ! 

Were you able to resolve your issue? Could you elaborate a bit more on why you think `ng-recaptcha` is the source of errors? I don't see any error lines in your webpack log that are `ng-recaptcha`-specific

**Comment by DethAriel** [comment]
@tonmoypaul reaching out to you again in case you missed my previous comment. I'd be keen to learn whether you were able to resolve this issue, and how if so?
