### ISSUE TITLE
Cannot determine the module for class RecaptchaComponent

### ISSUE THREAD

**Issue by chessmaster42** [DethAriel/ng-recaptcha#116]
### Summary

I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [x ] question / support request
- [ ] other

### Description
I am a getting the error on build of "Cannot determine the module for class RecaptchaComponent in ... Add RecaptchaComponent to the NgModule to fix it". This same error is mentioned over on #87 . I have both RecaptchaModule and RecaptchaFormsModule in the imports array of my feature module (not the root app module) and as such am importing RecaptchaModule as-is instead of as 'RecaptchaModule.forRoot()'.

Is there a problem with importing those modules into feature modules or is something else going on here?

Lib versions:

* ng-recaptcha: 4.0.0-beta.1
* Angular: 6.0.9
* Typescript: 2.7.2

**Comment by FlacosFlace** [comment]
Any updates on this? Did you solve the problem? I have the same..

**Comment by chessmaster42** [comment]
I haven't figured it out yet myself. Right now it's looking like I'm going to need to roll my own reCaptcha wrapper.

**Comment by FlacosFlace** [comment]
Did you already write your own wrapper?

**Comment by chessmaster42** [comment]
Nope, ended up just giving up on this library and changed over to this one: https://www.npmjs.com/package/ngx-captcha

**Comment by crankedapps** [comment]
I am able to use ng-recaptcha on a normal Angular 6 app however I'm seeing this same issue when trying to import RecaptchaModule in a module that's within an Angular Library.

**Comment by DethAriel** [comment]
Hi, everybody! This should be fixed with version 4.1.0 now, sorry it took so long!

**Comment by segux** [comment]
> Hi, everybody! This should be fixed with version 4.1.0 now, sorry it took so long!

Im on 4.2.1 and getting the same error. Did you sure is solved?

**Comment by vilbara** [comment]
Also getting this problem when compiling angular-cli library, using ng-recaptcha v4.1.0 and v4.2.1.

**Comment by vilbara** [comment]
This seems to be related how modules are structured in ng-recaptcha.

**A workaround:** Importing "RecaptchaCommonModule" in your application in addition to "RecaptchaModule" seem to solve the problem.
