### ISSUE TITLE
Recaptcha is not working on Angular5 MultiModule

### ISSUE THREAD

**Issue by santhoshrajuvysyaraju** [DethAriel/ng-recaptcha#117]
ERROR Error: "Uncaught (in promise): Error: Template parse errors:
'recaptcha' is not a known element:
1. If 'recaptcha' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
                <div class="row">
                  <div class="col-12">
                    [ERROR ->]<recaptcha formControlName="recaptchaResponse"> </recaptcha>

i got this error while running application.

**Comment by lavrik-av** [comment]
Got the same issue in my app after making a build --aot for "lazy" modules.
