### ISSUE TITLE
How to make it responsive ?

### ISSUE THREAD

**Issue by khetanrajesh** [DethAriel/ng-recaptcha#118]
### Summary

I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [x ] question / support request
- [ ] other

### Description
On mobile devices the captcha goes out of the div . 
![capture](https://user-images.githubusercontent.com/10100084/43047025-665eecdc-8def-11e8-8cf8-9b02d65f0ccc.PNG)

**Comment by smplyjr** [comment]
+1 for this, I have tried trick of scaling which you can find online to resize the reCAPTCHA but no luck.

**Comment by DethAriel** [comment]
Hi @khetanrajesh and @smplyjr !

This can be achieved via a wrapping `<div>` that has a `transform` property, see [this StackOverflow answer](http://stackoverflow.com/questions/27691411/change-new-google-recaptcha-width) or [this blog](https://geekgoddess.com/how-to-resize-the-google-nocaptcha-recaptcha/).

Here's a [life example](https://stackblitz.com/edit/ng-recaptcha-example-uncvxq?file=src/app/app.component.html) of `transform` property in action.

Please, let me know if that helps solve your issue
