### ISSUE TITLE
Bug on Edge browser with invisible recaptcha

### ISSUE THREAD

**Issue by FlorianSanchez** [DethAriel/ng-recaptcha#120]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description
Hello, i use Invisible recaptcha and i got a bug on Edge browser when i call execute methode.

recaptcha__fr.js (247,1312)
SCRIPT5007: Unable to get property 'prototype' of undefined or null reference

Lib versions:

* ng-recaptcha: 3.0.5
* Angular: 6.4.2
* Typescript (`tsc --version`): 2.9.2

**Comment by DethAriel** [comment]
Hi @FlorianSanchez , thx for taking the time to submit this!

Did the issue get resolved?

Unfortunately, the particular file where this error occurs, that is `recaptcha__fr.js`, is outside of my control - it's the core reCAPTCHA team who own that.

I'm afraid that without any further information I can't fix this. I you feel that it's indeed `ng-recaptcha` lib that causes this - please, feel free to reopen it and add a reproduction case - you can use [this Stackblitz demo](https://stackblitz.com/edit/ng-recaptcha-example) as a starting point
