### ISSUE TITLE
Pull Request - added manual error handler feature

### ISSUE THREAD

**Issue by Nelinho** [DethAriel/ng-recaptcha#122]
### Summary

I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [ ] question / support request
- [x] other

### Description
I implemented a error handler and would like to know if can I try a pull request to integrate the current solution?

The error callback can be used to manipulate visual feedback for users, eg. During the token request on invisible captcha, you can show a spinner and if something goes wrong you can handle it, because now you can get the event of errors and hide the spinner plus warning the user with your custom app dialog.

### Demo

<re-captcha 
    #recaptcha 
    size="invisible" 
    (resolved)="$event && onRecaptchaCallBack($event)"
    **(onError)="myErrorHandlerFunc()"**
    **[handleError]="true"**>
\</re-captcha>

* `onError()`. Optional, occurs when reCAPTCHA encounters an error (usually network connectivity) and cannot continue until connectivity is restored. If you specify (onError) and [handleError]="true", you are responsible for handle all errors and informing the user that they should retry.
* Important: To enable `onError()` callback, you must pass `[handleError]="true"` directive.

- [x] I did my best to come up with a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)

Lib versions:

* ng-recaptcha: 3.0.5
* Angular: 4.4.7
* Typescript (`tsc --version`): 2.9.2

**Comment by dockleryxk** [comment]
I had a look at your repo and I noticed two things:

1. I don't think the [handleError] is needed. You could just emit the error regardless. 
2. It would be more helpful if you emitted the actual error instead of just null.

**Comment by Nelinho** [comment]
Hi @dockleryxk ,

On item 1, if you set to handle errors manually, the captcha delivers to you the responsability and dont show errors alerts automatically anymore. You can't have the two ways in same time.

What I want to say is: I can't just emit the error regardless, cause if I set to emit the error, the captcha errors default behavior can not happens never again. So I though it would be interesting make it optional.

On item 2, I completely agree with you, but seems the reCaptcha do not send the error in $event object, just for that I'm sending null. If you know a way to catch the errors info, please let me know, it would be nice have this! I will continue looking for that!

Thanks for feedback!

**Comment by DethAriel** [comment]
Hello @Nelinho, and thx for reaching out!

I took a look at your commit, and it looks good!

To propagate the original parameters, we could do smth like that:

```ts
'error-callback': this.handleError ? (...args) => this.zone.run(() => this.captchaReponseError(...args)) : null,
```

I'd also default to `undefined` for `'error-callback'` if `handleError` has not been specified.

Other than that - please, feel free to submit a PR!
