### ISSUE TITLE
Cannot read property 'postMessageId' of null at onPostMessage (iframe.js:1000)

### ISSUE THREAD

**Issue by jalilzade** [DethAriel/ng-recaptcha#124]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description
I am receiving following error in console. but everything works fine. you can see error even your own Plunker demo. seems only happens in google chrome.

```
Uncaught TypeError: Cannot read property 'postMessageId' of null
    at onPostMessage (iframe.js:1000)
```

https://plnkr.co/edit/JNVNl0WJl3bFuWtt2O9i?p=preview

Lib versions:

* ng-recaptcha: 3.0.3 / 3.0.5
* Angular: 5.0.0
* Typescript (`tsc --version`): 3.0.1

**Comment by grvv** [comment]
Any fix yet?

**Comment by DethAriel** [comment]
Hello @jalilzade, and thx for taking the time to submit this!

Does it reproduce still? Surprizingly, I don't see it on the plunk. Could it be that this error was coming from either plunker, or from elsewhere (e.g. extensions)? To the best of my knowledge, the `iframe.js` file is not something that `ng-recaptcha` is in control of.

**Comment by jalilzade** [comment]
Hi @DethAriel thx for you clarification. As I said it only happens on chrome. I went deep on this according to your answer and disabled my installed extensions one by one on chrome. Finally I found that it is something related to `Wappalyzer v5.5.3` . Disabling this one solves the problem.

As you said it is not related to `ng-recaptcha`. 
Thank you.
