### ISSUE TITLE
Error encountered resolving symbol statically (AOT on production build)

### ISSUE THREAD

**Issue by bernardpolman** [DethAriel/ng-recaptcha#125]
### Summary

I'm submitting a: 
- [X] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description

I'm following your example of manually including the reCaptcha through <script> by following your example here: https://dethariel.github.io/ng-recaptcha/preload-api

The problem is that once I run "**ng build -prod -aot**" through Angular CLI on production build, I get the following error:

```
ERROR in Error encountered resolving symbol values statically. Calling function 'PreloadedRecaptchaAPIService', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in C:/PROJECTS/Domis-David/DomIS/development/DomIS.ResidentCareSpa/app/app.module.ts, resolving symbol AppModule in C:/PROJECTS/Domis-David/DomIS/development/DomIS.ResidentCareSpa/app/app.module.ts

ERROR in ./app/main.ts
Module not found: Error: Can't resolve './$$_gendir/app.module.ngfactory' in 'C:\PROJECTS\Domis-David\DomIS\development\DomIS.ResidentCareSpa\app'
 @ ./app/main.ts 4:0-70
 @ multi ./app/main.ts
```
The code is exactly the same as the one in your example I've linked above. 

Any suggestions?

**Comment by DethAriel** [comment]
Hi @bernardpolman ! Thx for submitting this!

Could you please specify angular and angular compiler versions that you are using?

**Comment by DethAriel** [comment]
@bernardpolman did you resolve this issue? I'm currently marking it as a candidate for closure due to inactivity, but I'd be glad to revisit that if you provide more information
