### ISSUE TITLE
Typescript Cannot find module 'ng-recaptcha'

### ISSUE THREAD

**Issue by goldman94** [DethAriel/ng-recaptcha#128]
### Summary

I'm submitting a: 
- [ x ] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description
I updated the package and now the Typescript transpile fails saying it cannot find the module 'ng-recaptcha'. I checked the ng-recaptcha folder within npm_modules and found no JS or TS files at all. 
<img width="178" alt="screen shot 2018-10-24 at 4 55 30 pm" src="https://user-images.githubusercontent.com/35706971/47464038-a6a5d500-d7ad-11e8-8a8d-d2d7ba878808.png">

**Comment by DethAriel** [comment]
@goldman94 good find! I'm about to republish the package, this will be fixed in a couple minutes!

**Comment by goldman94** [comment]
@DethAriel Thank you!

**Comment by DethAriel** [comment]
`v4.2.1` fixes it, sorry for the mess-up
