### ISSUE TITLE
RECAPTCHA_NONCE Does not work

### ISSUE THREAD

**Issue by Crounini** [DethAriel/ng-recaptcha#130]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [X] question / support request
- [ ] other

### Description

The new RECAPTCHA_NONCE option seems to not work properly

Following the official ReadMe, it seems that the new TOKEN RECAPTCHA_NONCE does not add a nonce='' option in script api.js tag.

Added the: 
providers: [
  {
    provide: RECAPTCHA_NONCE,
    useValue: '554dfsdf65dgfdf5g4hrthefe44',
  },
  {
    provide: RECAPTCHA_LANGUAGE,
    useValue: 'fr',
  },
],
In ngModule providers section but the result is only:
<script src="https://www.google.com/recaptcha/api.js?render=explicit&amp;onload=ng2recaptchaloaded&amp;hl=fr" async="" defer=""></script>

Also tested others token like RECAPTCHA_LANGUAGE or RECAPTCHA_BASE_URL with success in the same configuration.

Do I make an error somewhere ?

Lib versions:

* ng-recaptcha: 4.2.1
* Angular: 6.1.10
* Typescript (`tsc --version`): (2.7.2?)

**Comment by DethAriel** [comment]
@Crounini which browser are you using? As you can see by [this example](https://stackblitz.com/edit/ng-recaptcha-example-8ifwys?file=src%2Fapp%2Fapp.component.ts), the `nonce` attribute is actually set correctly. But what happens is (and you can see it in the below screenshot) is that Chrome hides this value from the markup that it shows in the dev panel:

<img width="1045" alt="screen shot 2019-02-01 at 2 21 08 pm" src="https://user-images.githubusercontent.com/1497789/52152847-cb231000-262c-11e9-942f-3c1179058e8f.png">

The bottomline is - attribute is there :) Hope that helps
