### ISSUE TITLE
Submitting form several times with invisible re-captcha

### ISSUE THREAD

**Issue by progist1** [DethAriel/ng-recaptcha#131]
### Summary

I'm submitting a: 
- [ ] bug report
- [x] question / support request
- [ ] feature request
- [ ] other

### Description
I am trying to place a reactive form with invisible `<re-captcha>`:
```
<form [formGroup]="loginForm" (ngSubmit)="captchaRef.execute()">
<...>
<re-captcha
		(resolved)="$event && onSubmitLoginForm($event)"
		#captchaRef="reCaptcha"
		size="invisible"
  ></re-captcha>
</form>
```
in `.ts`:
```
public onSubmitLoginForm(captcha: string): void {
	this.submitLoginForm(captcha);
}
```
If user tries to submit login form first time, everything goes smoothly. Server validates answer from reCaptcha. But if authentication is unsuccessful, submitting form second time doesn't bring any result. 
I think it's about `(resolved)="$event` problem, because, submitting the form second time don't achieve `onSubmitLoginForm`.

Do you have any suggestions how to fix that?

Thank you.

* ng-recaptcha: 4.2.1
* Angular: 6.0.8
* Typescript (`tsc --version`): 2.7.2

**Comment by DethAriel** [comment]
Hello @progist1 ! 

The expected usage in this case is to reset the component upon error response from the server, e.g.:

```ts
import { catchError } from 'rxjs/operators';

/* ... */

@ViewChild('captchaRef')
public recaptchaComponent: RecaptchaComponent;

public onCaptchaResolved(captcha: string): void {
  // assumes that `submitForm` returns an `Observable`
  this.submitForm(captcha).pipe(catchError(e => {
    this.recaptchaComponent.reset();
  }));
}
```

Alternatively, you could do that in the template itself:

```html
<form [formGroup]="loginForm" (ngSubmit)="captchaRef.execute()">
<...>
<re-captcha
		(resolved)="$event && onSubmitLoginForm($event) && captchaRef.reset()"
		#captchaRef="reCaptcha"
		size="invisible"
  ></re-captcha>
</form>
```
