### ISSUE TITLE
Error: Missing required parameters: sitekey When Unit Testing

### ISSUE THREAD

**Issue by blogcraft** [DethAriel/ng-recaptcha#132]
### Summary

I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [X] question / support request
- [ ] other

### Description
I have some components which have the ng-recaptcha. And in some random test there is sometimes an error:
Error: Missing required parameters: sitekey

I guess I have to add a provider with the settings in my spec files?
The problem is that the error **is not consistent**, sometimes it pops up sometimes not.

### Demo

No demo, sorry :/

Lib versions:

* ng-recaptcha: 4.2.1
* Angular: 7.1
* Typescript (`tsc --version`): 3.1.6

**Comment by MicMicMon** [comment]
Put your RECAPTCHA_SETTINGS provider in your test file where you setup your testbed:

```
TestBed.configureTestingModule({
// ...
providers: [
//...
,{
    provide: RECAPTCHA_SETTINGS,
    useValue: { siteKey: 'yoursitekey' } as RecaptchaSettings,
  }
//...
});
```

with the proper module imports (RecaptchaModule, RecaptchaFormsModule).

**Comment by DethAriel** [comment]
Hello @blogcraft !

Did the suggestion by @MicMicMon resolve your issue? If it did not, I would ask you to provide more information on this issue:

* what kind of test is that? E.g. unit/e2e?
* what environment is the test running in? E.g. browser/node?

This error is not something that this lib generates - it's reCAPTCHA itself who throws it, hence I'm assuming you're running an end-to-end test in browser environment. If so, I'd recommend you to check out Google documentation section on [automated testing with reCAPTCHA](https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha-what-should-i-do).

Please do let me know whether the above suggestion helped to resolve your issue, or if you resolved it yourself - how did you do it (so we can potentially update the library's docs to encompass your usage scenario).
