### ISSUE TITLE
Correct recaptcha version for the plugin

### ISSUE THREAD

**Issue by eaponiente** [DethAriel/ng-recaptcha#137]
What is the correct recaptcha version to use in this plugin? I tried the v2 checkbox and the v3 recaptcha site key but I'm still getting this error

```
Error for site owner: Invalid key type
```

**Comment by DethAriel** [comment]
Hi! Could you please give a code example of how you’re providing the site key and getting the recaptcha token? It’s very different for recaptcha v2 and v3. Also, recaptcha v3 support is currently only in the beta version of the package

**Comment by eaponiente** [comment]
Hi @DethAriel 

This is my form reactive which contains the recaptcha

from my component.ts
```
this.registrationForm = this.fb.group({
      first_name: ['', [Validators.required]],
      recaptcha: [null, Validators.required]
    });
```

from html.component.ts
```
<re-captcha siteKey="someSiteKeyFromGoogle" formControlName="recaptcha"></re-captcha>
```

this is what I added to my `app.module.ts` in imports

```
RecaptchaFormsModule,
RecaptchaModule
```

**Comment by DethAriel** [comment]
@eaponiente this seems to be right. For usage with `re-captcha` component you need reCAPTCHA v2 site key, which you can also provide via `RECAPTCHA_SETTINGS` injection token, see [this example](https://github.com/DethAriel/ng-recaptcha#example-global-config). I'd suggest you to double check that the key you're using is for reCAPTCHA v2 **and** that it is configured to allow `localhost` domain specifically (in case you're encountering that error during local development).

Let me know how this goes!

**Comment by eaponiente** [comment]
wow! it worked when I tried the global configuration. this is weird because what I used before was not the global configuration

but I will stick with this one for now
