### ISSUE TITLE
Google reCaptcha challenge popup not displaying properly in Mat Dialog

### ISSUE THREAD

**Issue by suhelkhan1** [DethAriel/ng-recaptcha#138]
### Summary

I'm submitting a: 
- [x] bug report

### Description

I added google reCaptcha in angular material dialog form. But when reCaptcha opens verification popup, it display above the form like in pic.
![captcah-popup](https://user-images.githubusercontent.com/28000974/53730293-87c2f800-3e9d-11e9-933b-a669a322e7c5.jpg)

### Cause of problem
I also found that whenever mat dialog opens it adds the negative margins to the html tag. And if I remove the margin the captcha verification popup goes into right place but then mat dialog not display properly. I am confused how to make both popup in right place.

**Comment by romelgomez** [comment]
This project doesn't add any styles that can't affect the default behavior. 

Go to: https://github.com/angular/material2 to log the issue. 

I do recommend implement a simple example in stackblitz.

**Comment by DethAriel** [comment]
Hi @suhelkhan1 ! As mentioned by @romelgomez, this bug does indeed belong to the material project, there's no css additions that `ng-recaptcha` does. If you already submitted an issue - could you maybe link it here as a comment so that others can follow the resolution?

**Comment by amine-iratni** [comment]
Hi @suhelkhan1 do you have a scroll on the main page? If so, can you scroll to top before you open the dialog then trying to show the recaptcha?

**Comment by amitsharma9696** [comment]
Hi @suhelkhan1 use  window.scrollTo(0, 0) before opening the dialog
  openDialog(): void {
    window.scrollTo(0, 0)
    const dialogRef = this.dialog.open(ComponentName, {});
 }

**Comment by Atom02** [comment]
> Hi @suhelkhan1 use window.scrollTo(0, 0) before opening the dialog
> openDialog(): void {
> window.scrollTo(0, 0)
> const dialogRef = this.dialog.open(ComponentName, {});
> }

is this the only way?

**Comment by PhilippMeissner** [comment]
> > Hi @suhelkhan1 use window.scrollTo(0, 0) before opening the dialog
> > openDialog(): void {
> > window.scrollTo(0, 0)
> > const dialogRef = this.dialog.open(ComponentName, {});
> > }
> 
> is this the only way?

Yes.
The only, possibly not viable, option would be to change the style reCAPTCHA applies to its DOM element. The second container being rendered (the one that actually includes the iFrame of reCAPTCHA) holds a style attribute of `position: absolute`. If you change this to `position: fixed` the position of the reCAPTCHA overlay will be within the viewport. But again, I don't think this is a viable solution..
