### ISSUE TITLE
Maximum call stack size exceeded using reset() method

### ISSUE THREAD

**Issue by ViieeS** [DethAriel/ng-recaptcha#139]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description
Infinity loop if validate a form after resolve captcha. See demo.

### Demo

https://stackblitz.com/edit/ng-recaptcha-example-xhwtud

Lib versions:

* ng-recaptcha: 4.2.0
* Angular: 7.3.6
* Typescript (`tsc --version`): 3.2.4

**Comment by DethAriel** [comment]
@ViieeS thx for submitting this!

The `(resolved)` event is triggered when you invoke `captchaRef.reset()` method, which in turn triggers `(resolved)` event, and that's how an infinite loop is achieved. To overcome that you need to check the captcha response:

```html
<re-captcha (resolved)="sendForm($event)"></re-captcha>
```

```ts
  public sendForm(response: string) {
    if (response) {
      // send response to the server along with form values
      this.captchaRef.reset();
    }
  }
```

Let me know if this doesn't help!
