### ISSUE TITLE
Tests fail: No value accessor for form control with name: 'recaptcha'

### ISSUE THREAD

**Issue by cfood** [DethAriel/ng-recaptcha#140]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description

I've implemented the recaptcha plugin which works in the browser. However, the Jasmine tests fail with "No value accessor for form control with name: 'recaptcha'".

RecaptchaModule and RecaptchaFormsModule are both imported in the spec.ts file.

**Comment by romelgomez** [comment]
"No value accessor for form control with name: 'recaptcha'". 

The `recaptcha` input, has its counterpart defined in FormGroup

```
<input formControlName="recaptcha" >
```

```
    this.formInstance = new FormGroup ({
      email: new FormControl('', [
        Validators.required,
        Validators.email,
      ]),
      password: new FormControl('', [
        Validators.required,
        Validators.minLength(8),
      ]),
      rememberMe: new FormControl(false, []),
      recaptcha: new FormControl('', [])
    });
```

**Comment by DethAriel** [comment]
@cfood could you please provide the code example that illustrates the issue? Have you been able to fix it, by any chance?

**Comment by geyuqiu** [comment]
ngDefaultControl
