### ISSUE TITLE
ViewEncapsulation.ShadowDom causes a blocked frame with origin "https://www.google.com" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by apesteguy** [DethAriel/ng-recaptcha#143]
# 🚀 feature request

### Relevant Package

@angular-devkit/architect    0.13.7 (cli-only)
@angular-devkit/core         7.3.7 (cli-only)
@angular-devkit/schematics   7.3.7 (cli-only)
@schematics/angular          7.3.7 (cli-only)
@schematics/update           0.13.7 (cli-only)
rxjs                         6.4.0
 "ng-recaptcha": "^4.3.0"

### Description
I am trying to display google ``reCAPTCHA`` inside a component from my application. 

- For some reasons, I must encapsulate this component from my application. To do that I am using ``ViewEncapsulation.ShadowDom``. 

- From the ``app.module.ts`` I have installed ``RecaptchaModule``

My issue is about the ``reCAPTCHA`` <=> ``ViewEncapsulation.ShadowDom``. 

From what I can tell, the ``ViewEncapsulation.ShadowDom`` blocks the iframe reCAPTCHA from google to work as expected. 

If I remove the ``ViewEncapsulation.ShadowDom`` from my component everything works fine :-)
But if I add the ``ViewEncapsulation.ShadowDom`` and then run the application the console displays the following issue message: 
> recaptcha__en.js:527 Uncaught DOMException: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame. 

Does the use  of ``ShadowDom``  means that we cannot use reCAPTCHA ? Is there another way to use reCAPTCHA if handled inside a Shadow Dom ?

**Comment by DethAriel** [comment]
Hi @apesteguy and thx for submitting this 👍 

Yes, reCAPTCHA does not play well with Shadow DOM. However, you can still make it work. Below is what you need to do (spoiler: slotting and some prop propagation).

Keep your encapsulated component as `ViewEncapsulation.ShadowDom`, but where you previously had `<re-captcha>` element, make it a `<slot name="recaptcha-slot"></slot>`

I assume your encapsulated component needs access to at least recaptcha value and maybe its `reset()` method, so those will have to be propagated. Add `@Input() recaptchaValue: string | null;` and `@Output() recaptchaReset = new EventEmitter();` to your component.

From then on, where you were previously using your component (let's say it's called `my-comp`), change the usage sites from 

```
<my-comp></my-comp>
```

to 

```
<my-comp
  [recaptchaValue]="propagatedValue"
  (recaptchaReset)="captchaRef.reset()"
>
  <span slot="recaptcha-slot">
    <re-captcha
      #captchaRef="reCaptcha"
      (resolved)="propagatedValue = $event"
    ></re-captcha>
  </span>
</my-comp>
```

Essentially, this usage site can now become your "actual" `<my-comp>`, and what you had previously can be renamed to `<my-comp-impl>`. Notice, that wherever `<re-captcha>` is used, `ViewEncapsulation.Emulated` is expected.

To better illustrate this concept, I've crafted a demo that you can use for reference purposes, you can find it [here](https://stackblitz.com/edit/angular-2ehak8?file=src%2Fapp%2Fencapsulated.component.ts).

Please let me know if this approach satisfies your requirements, or if you have any additional ones that I might not have covered.

**Comment by apesteguy** [comment]
Thanks @DethAriel for you great answer ! It works perfectly on my side. So congratulations and thanks for your help :+1:  Also note that I tried using the ng-recaptcha verison 3 and it seems working with ```ViewEncapsulation.ShadowDom``` so that now I have both options using the version 2 and the version 3 :-)

**Comment by camilo-17** [comment]
Hi!
Is there any way to make it works on firebase auth with phone number ?
basically I have the same problem but with firebase the recaptcha is auto generated using this:

`  this.windowRef.recaptchaVerifier = new firebase.auth.RecaptchaVerifier('recaptcha-container');`
