### ISSUE TITLE
Broken in IE11

### ISSUE THREAD

**Issue by JohnnyQQQQ** [DethAriel/ng-recaptcha#145]
### Summary

I'm submitting a: 
- [X] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description

ng-recaptche seems to be broken in IE11. When loaded it also breaks `HttpParams` of angular for some reason. Any `HttpParams` objects just become empty.

### Demo

https://stackblitz.com/edit/angular-ppr2wq (stackblitz is also broken, but one can grab the code to get a quick demo locally)

**Comment by DethAriel** [comment]
hi @JohnnyQQQQ , and thx for reaching out!

The `polyfills.ts` file contains some commented-out lines which are supposed to make IE11 work with Angular. You should uncomment those and try again. If you still see the error - do you mind posting it here for further resolution? if it helps - let me know anyway ;)

**Comment by JohnnyQQQQ** [comment]
Thanks for the catch - and sorry for the noise 👍
