### ISSUE TITLE
Captcha fails to load if screen size is too small

### ISSUE THREAD

**Issue by sjyn** [DethAriel/ng-recaptcha#150]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description
When running in a mobile view (chrome, Nokia Lumina 520), if the screen size is too small then the captcha fails to render and an error is thrown.

To Reproduce: Change your chrome browser to mobile view and select the Nokia Lumnia 520 option. Refresh the page. An error will be thrown saying that the name of a particular iframe is invalid, and no captcha will render.

### Demo

- [x] I did my best to come up with a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)

Stackblitz demonstrating the issue:
https://stackblitz.com/edit/angular-dm4yef

Lib versions:

* ng-recaptcha: ^5.0.0
* Angular: 8.0.0
* Typescript (`tsc --version`): ~3.1.1

**Comment by DethAriel** [comment]
Hi @sjyn !

Seems to work for me on smaller screen sizes. If you're still encountering this issue -- could you please elaborate on what is the error you're seeing? A screen capture would help, too
