### ISSUE TITLE
Recaptcha v3 loads on all pages with a form

### ISSUE THREAD

**Issue by andpozo** [DethAriel/ng-recaptcha#153]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [x] question / support request
- [ ] other

### Description

I have a problem when try to integrate recaptcha v3 in mi angular app, the problem is when I register the provider, captcha is displayed in all component with a form inside, any one can help me? Really is so weird...

Thanks a lot!

**Comment by psenechal** [comment]
My issue is similar, but a tad different. If I load a component that just has static text on it (no forms, recaptcha service not injected), the badge does not display. As soon as I navigate to a component with a form and the recaptcha service injected, the badge displays. Navigating back to that original component and the badge still remains on the page.

Is there a way to remove the badge onDestroy of a component?

**Comment by psenechal** [comment]
I did a little research and this may be what is intended with v3 since it looks like it attempts to build a profile of the user's actions to determine if they're a bot or not.

I decided the easiest approach was just to hide the badge by default and then unhide it on pages where I want it to display. I accomplished this by adding a global style and a class specific style

`
// hide recaptcha badge
.grecaptcha-badge {
  visibility: hidden;
}

// only show recaptcha badge on needed pages
body.recaptcha {
  .grecaptcha-badge {
    visibility: visible;
  }
}
`

on components where I want to display the badge, I add a "recaptcha" class to the body in OnInit and remove it in OnDestroy. I'm using Angular Universal, so I have to check to make sure I'm in the browser

`
  ngOnInit(): void {
    if (isPlatformBrowser(this._platformId)) {
      this._document.body.classList.add('recaptcha');
    }
  }

  ngOnDestroy(): void {
    if (isPlatformBrowser(this._platformId)) {
      this._document.body.classList.remove('recaptcha');
    }
  }
`

Hope that helps someone.

**Comment by Dilshan97** [comment]
I have same issue. this is the way i fix it. i don't know this method is the best solution for this problem.

import { Component, OnInit, OnDestroy, Injector } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { ReCaptchaV3Service } from 'ng-recaptcha';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-forgot-password',
  templateUrl: './forgot-password.component.html',
  styleUrls: ['./forgot-password.component.scss']
})
export class ForgotPasswordComponent implements OnInit, OnDestroy {

  forgotPassword: FormGroup;
  private subscription: Subscription;

  constructor(
    private fb: FormBuilder,
    private recaptchaV3Service: ReCaptchaV3Service,
  ) {

  }

  ngOnInit() {
    this.forgotPassword = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      recaptcha: ['', Validators.required]
    });

    this.subscription = this.recaptchaV3Service.execute('forgot_password').subscribe((token) => {
      this.forgotPassword.patchValue({
        recaptcha: token
      });

      let element = document.getElementsByClassName('grecaptcha-badge');
      element[0].setAttribute('id', 'grecaptcha_badge');
      document.getElementById('grecaptcha_badge').style.display = 'block';
    });
  }

  ngOnDestroy() {
    if (this.subscription) {
      this.subscription.unsubscribe();
    }
    let element = document.getElementsByClassName('grecaptcha-badge');
    element[0].setAttribute('id', 'grecaptcha_badge');
    document.getElementById('grecaptcha_badge').style.display = 'none';
  }
}

**Comment by timhecker** [comment]
@Dilshan97 Thanks for your solution, at the moment it works pretty fine. I only added a little control on `ngOnInit()` method:
```ts
if (element && element[0]) {
 ...
}
```

**Comment by mrpetem** [comment]
Based on @psenechal solution, you can achieve this without injecting dependencies and just use Renderer2 in the component where you want the badge to display:

`
import { Component, OnInit, OnDestroy, Renderer2 } from '@angular/core';
...

export class MyComponent implements OnInit, OnDestroy {

    constructor(
        ...
        private renderer: Renderer2,
        private recaptchaV3Service: ReCaptchaV3Service,
        ) {}

    ngOnInit(): void {
        this.renderer.addClass(document.body, 'recaptcha');
    }

    ngOnDestroy() {
        this.renderer.removeClass(document.body, 'recaptcha');
    }

}
`

CSS:
`/* hide recaptcha badge*/
.grecaptcha-badge {
	visibility: hidden;
}

/* only show recaptcha badge on needed pages */
body.recaptcha .grecaptcha-badge {
	visibility: visible;
}`

**Comment by DethAriel** [comment]
Hey all! I see that you've resolved this issue already, but I wanted to call out that this is indeed _expected behavior_. To help others discover this, I've added a small [section](https://github.com/DethAriel/ng-recaptcha#hiding-recaptcha-badge) to the project's README, which essentially simply points to [reCAPTCHA documentation](https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed). It is worth noting, however, that if you hide the badge, reCAPTCHA terms of service **require** you to include the branding visibility in a way that would be perceivable by your users (the FAQ link gives a good example of doing this).

Cheers!
