### ISSUE TITLE
NgRecaptchaV3 integration issue

### ISSUE THREAD

**Issue by shalini2200** [DethAriel/ng-recaptcha#154]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description

I want to integrate ng-Recapcha for version 3 in angular 8 application but I unable to integrate.Can you please provide me better solutions.
Thanks
[ng-recaptcha-example.zip](https://github.com/DethAriel/ng-recaptcha/files/3765854/ng-recaptcha-example.zip)

**Comment by shalini2200** [comment]
I tryed to integrate ngRecaptchaV3 into my angular 8 application but I unable to integrate when I install ngRecaptcha and use v3 secret key than it is  not working.

**Comment by DethAriel** [comment]
@shalini2200 can you please summarize the issue you're facing here instead of attaching a zip file? An example of v3 integration can also be found here: https://dethariel.github.io/ng-recaptcha/v3

**Comment by shalini2200** [comment]
> @shalini2200 can you please summarize the issue you're facing here instead of attaching a zip file? An example of v3 integration can also be found here: https://dethariel.github.io/ng-recaptcha/v3

@DethAriel I want to integrate recaptcha v3 on login page. I am able to get  access token after that what should I do, how I differentiate human and bot.
