### ISSUE TITLE
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute.

### ISSUE THREAD

**Issue by zohaibarshad-tkxel** [DethAriel/ng-recaptcha#157]
Hey, I am getting following warnings on console when i use ng-recaptcha

![Captcha-Console_errors](https://user-images.githubusercontent.com/52048120/68924295-457ae600-07a2-11ea-9008-01896b8b2729.png)

As per google chrome they will release a version in February 2020 which will not allow these cookies any more. So kindly look into.

https://support.google.com/chrome/thread/16654793?hl=en

**Comment by Sampath-Lokuge** [comment]
Yes, I have the same issue. Any workaround for this?

**Comment by DethAriel** [comment]
Hi folks!

`ng-recaptcha` lib does not set, read, or update cookies -- this functionality is part of reCAPTCHA core code. Unfortunately, there's nothing this lib can do about it.
