### ISSUE TITLE
"Invalid operand to 'instanceof': Function expected" 

### ISSUE THREAD

**Issue by spock123** [DethAriel/ng-recaptcha#158]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description

I am using ng-captcha as v2 invisible. It works perfectly except for Microsoft Edge browser.

The error I get is:

`"Invalid operand to 'instanceof': Function expected" `

 
Any idea why?

The most crazy thing is that it works in IE 11

**Comment by petyappetrov** [comment]
Same problem. Anyone have a solution?

**Comment by DethAriel** [comment]
Hi @spock123 and @petyappetrov !

Is this still an issue? There's only a single place where `instanceof` operator is used in `ng-recaptcha` code (it's [here](https://github.com/DethAriel/ng-recaptcha/blob/9395b82364ff852f7359949a679fc7ce72ab9bee/recaptcha/recaptcha.component.ts#L66)), and, surely, it must succeed in Edge, mustn't it?

**Comment by spock123** [comment]
Hi @DethAriel , it was an issue in a specific version of Edge.

Now with the new Chromium based version is default, we can close this comment. Don't think there are users in the wild with this version any longer.
