### ISSUE TITLE
Build Optimizer causes null reference in RecaptchaLoaderService

### ISSUE THREAD

**Issue by MattSenter** [DethAriel/ng-recaptcha#160]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description

`RecaptchaLoaderService` is expected to have a `ready` member at time of construction, but this member only exists in a non-optimized build. If you set `buildOptimizer: true` in `angular.json`, you will get a null reference error on line 73, https://github.com/DethAriel/ng-recaptcha/blob/c50d26c6c90acfa45aa349b73562fac3c4e06991/recaptcha/recaptcha-loader.service.ts#L73. `RecaptchaLoaderService.ready.asObservable()` throws the error.

### Demo

First build and serve your project with `buildOptimizer: false`. The `RecaptchaLoaderService.ready.asObservable()` will pass successfully.

Next, build and serve your project with `buildOptimizer: true`. `RecaptchaLoaderService.ready.asObservable()` will throw a null reference error.

- [x] I did my best to come up with a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)

Lib versions:

* ng-recaptcha: 5.0.0
* Angular: 7.2.15
* Typescript (`tsc --version`): 3.1.6

**Comment by DethAriel** [comment]
Hi @MattSenter! I'm sorry it took so long to get back to you.

It seems that the issue has been fixed, as I'm now able to use `"buildOptimizer": true` flag in both Angular 9 and Angular 10 projects.

Thank you for being so proactive as to even submit a PR to fix this!

**Comment by MattSenter** [comment]
We are in the process of updating to ng10, so I'll let you know what I see. thanks!
