### ISSUE TITLE
resolved is not being called for invisible captcha In angular 8

### ISSUE THREAD

**Issue by vikas112dubey** [DethAriel/ng-recaptcha#162]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [x] question / support request
- [ ] other

### Description
i am trying to implement invisible captcha. For normal one it seems to work fine. But for the invisible captcha the resolved callback is never called.
I have gone through a lot of demo but most of them don't go beyond angular 6.

following is very simple code to reproduce the same.

```html
<!-- app.component.html -->
<div>
  <h3>Invisible CAPTCHA</h3>
  <re-captcha size="invisible" siteKey="6LenCMcUAAAAAKVovA9nmHSMx7ptJce4qAXVhd_9" ``#captchaRef="reCaptcha" (resolved)="onResolve($event)"></re-captcha>
  <button (click)="resetCaptcha()">Reset</button>
  <h4>Invisible captcha response</h4>
  <pre>{{ response || "empty"}}</pre>
</div>
```

```ts
// app.component.ts

import { Component, VERSION, ViewChild, AfterViewInit } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';

import { RecaptchaComponent } from 'ng-recaptcha';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.scss' ]
})
export class AppComponent implements AfterViewInit {
  response: string;

  @ViewChild("captchaRef", {static: true}) public captchaRef: RecaptchaComponent;

  public ngAfterViewInit() {
    this.captchaRef.execute();
  }

  public resetCaptcha() {
    this.captchaRef.reset();
  }
  onResolve(captchaResponse: string) {
    this.response = captchaResponse;
  }
}
```

let me know if i am missing something here.
Thanks in advance for your help.

Lib versions:

* ng-recaptcha: 5.0.0
* Angular: 8.0.3
* Typescript (`tsc --version`): 3.4.3

**Comment by ishaarawy** [comment]
same issue

**Comment by DethAriel** [comment]
Hi @vikas112dubey and @ishaarawy ! Were you able to resolve the problem?

Also, could you elaborate on why `static` flag is set to `true` in your example, please?
