### ISSUE TITLE
Ability to lazy load reCAPTCHA v3 site key

### ISSUE THREAD

**Issue by envig** [DethAriel/ng-recaptcha#165]
### Summary

I'm submitting a: 
- [ ] bug report
- [x] feature request
- [ ] question / support request
- [ ] other

### Description
Currently the v3 site key can only be provided by the `RECAPTCHA_V3_SITE_KEY` injection token which is of type `string`. It would be nice to have the ability to lazy load the site key (for example via a REST call) and assign it to the `ReCaptchaV3Service` once it's loaded.

**Comment by irvjc82** [comment]
+1

**Comment by berestovyyig** [comment]
Hello tell me please how to user dark theme with reCAPTCHA v3?

**Comment by DethAriel** [comment]
Hi @envig !

Could you please elaborate a bit more on your use-case? It appears to be quite exotic at this point, but maybe if I learn more about it, I can suggest a path forward.

Out the top of my head, this should work:
* create a lazy-loaded `NgModule` X to which you'll provide the captcha token from REST endpoint
* this module, in turn, will import `RecaptchaModule`, and provide the token to it

Do you think that will work?

**Comment by ayush013** [comment]
Hi @DethAriel, 

The idea is to conditionally load the RECAPTCHA_V3_SITE_KEY (from an API call preferably) and then useValue for the provider.

We have something similar in Angular using APP_INITIALIZER. It enables us to use a certain value from config instead of hardcoding it in the module and services.

` {
      provide: APP_INITIALIZER,
      useFactory: initApp,
      multi: true,
      deps: [ConfigService]
    },`

[Full example here](https://davembush.github.io/where-to-store-angular-configurations/)

**Comment by ashishgehlot** [comment]
I created a workaround to make it dynamic or via rest api using '**useFactory**'.

```
providers: [{
    provide: APP_INITIALIZER,
    useFactory: onAppInit,
    multi: true,
    deps: [ConfigService]
  },
{ provide: RECAPTCHA_V3_SITE_KEY, useFactory: LoadRecaptchKey } ]


export function LoadRecaptchKey() {
    return CaptchaKey;
}

export function onAppInit(configService: ConfigService): () => Promise<any> {
    return (): Promise<any> => {
        return new Promise((resolve, reject) => {
            configService.setConfiguration((appsettings: any) => {
                    CaptchaKey = appsettings.ReCaptchaSiteKey;
                    resolve();
            });
        });
    };
}
```

**Comment by JakubPawlak** [comment]
I have a similar requirement for async key injection. 

ReCaptcha public key is requested from backend depending on the environment of the app is running on. Workaround with APP_INITIALIZER above should work, but what if backend is temporary unavailable? The whole app wouldn't be loaded or it would wait in a blank state during retry.

**Comment by DethAriel** [comment]
There is now an idiomatic way to achieve that with Angular, which is using [`APP_INITIALIZER`](https://angular.io/api/core/APP_INITIALIZER). The approach is demonstrated in [this Stackblitz demo](https://stackblitz.com/edit/ng-recaptcha-example-3txhms). In essence, here's what's being done there:

```typescript
// config.service.ts
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ConfigService {
  public recaptchaSiteKeyV2: string | null = null;
  public recaptchaSiteKeyV3: string | null = null;

  public async loadConfig(): Promise<void> {
    const { siteKeyV2, siteKeyV3 } = await fetchConfig(/* some API call */);
    this.recaptchaSiteKeyV2 = siteKeyV2;
    this.recaptchaSiteKeyV3 = siteKeyV3;
  }
}

// app.module.ts
import { APP_INITIALIZER, NgModule } from '@angular/core';
import { RECAPTCHA_SETTINGS, RecaptchaSettings, RECAPTCHA_V3_SITE_KEY } from 'ng-recaptcha';

import { ConfigService } from './config.service';

function appLoadFactory(config: ConfigService) {
  return () =>
    config.loadConfig().then(() => console.log(`config resolved`, config));
}

@NgModule({
  providers: [
    {
      provide: RECAPTCHA_V3_SITE_KEY,
      useFactory: (config: ConfigService) => {
        return config.recaptchaSiteKeyV3;
      },
      deps: [ConfigService]
    },
    {
      provide: RECAPTCHA_SETTINGS,
      useFactory: (config: ConfigService): RecaptchaSettings => {
        return { siteKey: config.recaptchaSiteKeyV2 };
      },
      deps: [ConfigService]
    },
    {
      provide: APP_INITIALIZER,
      useFactory: appLoadFactory,
      deps: [ConfigService],
      multi: true
    }
  ]
})
export class AppModule {}
```
