### ISSUE TITLE
Value at position x in the NgModule.imports of AppModule is not a reference: [object Object]

### ISSUE THREAD

**Issue by nrone** [DethAriel/ng-recaptcha#167]
### Summary

I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [ ] question / support request
- [x] other

### Description

Upgradeing to Angular9 and using RecaptchaModule.forRoot() breaks the app. Remove the .forRoot() fixes this. However, this wasent very clear from the insane amounts of errors that came. Others might run into this issue, and this is why i decided to post it here.

.forRoot() was once required to setup 
https://github.com/DethAriel/ng-recaptcha/commit/7fb97fb04049dd058a2394ecef297dac7c6104d1#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by aipirvu** [comment]
+1

I got here because I was expecting some sort of issue announcing that `.forRoot()` is deprecated.

**Comment by Hassan-Moin** [comment]
+1. Got me stuck in update to Angular 9, when I was running `ng build --prod` possibly due to AOT or buildOptimizer. 
`ng build` or `ng serve` worked as it should. 
After countless iterations of removing modules, I found out that `ng-recaptcha` was the issue. Removed it, my project build correctly. 
Stumbled upon this issue, added the module back and removed `.forRoot()` and this fixed the issue.

**Comment by Abubarrett** [comment]
removing .forRoot() doesn't fix the issue it just lets the app compile but i still get an error when the app is running
<img width="671" alt="Screen Shot 2020-02-12 at 10 06 08" src="https://user-images.githubusercontent.com/16496489/74353328-5e823b80-4d7f-11ea-9e52-f7779877aaf1.png">

**Comment by Liword38** [comment]
+1 Thanks a lot. 
As a begginer I was struggling for so long with those error messages and your solution fixed it perfectly.

**Comment by DethAriel** [comment]
Thx for submitting this @nrone !

Removing `.forRoot` should have been a think I did long ago, but it has slipped v5 and v6 releases of `ng-recaptcha`. I'm sorry you ran into this issue, mate!

**Comment by DethAriel** [comment]
The `.forRoot` deprecated method has been removed in v7.0.0. Happy coding, y'all!
