### ISSUE TITLE
Angular 9 - Ivy compatibility

### ISSUE THREAD

**Issue by Dugnychon** [DethAriel/ng-recaptcha#168]
### Summary

I'm submitting a:
- [ ] bug report
- [X] feature request
- [X] question
- [ ] other

### Description

Right now, we have when using ng-recaptcha with Angular 9, you get a warning `warning " > ng-recaptcha@5.0.0" has incorrect peer dependency "@angular/core@^6.0.0 || ^7.0.0 || ^8.0.0".`.

There are no errors and everything work expected (for us), when using ng-recaptcha with ReCAPTCHA v2 on our Angular 9 codebase but only this warning.

I don't know if the module needs more work for Angular 9 full compatibility, or if only the dependency version should be bumped if everything works as expected.

Does anybody has more information regarding Angular 9/Ivy and ng-recaptcha? 
Thanks in advance!

* ng-recaptcha: 5.0.0
* Angular: 9.0.22
* Typescript (`tsc --version`): 3.7.5

**Comment by Toktik** [comment]
With ivy enabled we are getting errors while importing the module. Ng-recaptcha must generate proper .metadata.json file.

**Comment by ezequieltejada** [comment]
I have this error:

ERROR in node_modules/ng-recaptcha/recaptcha/recaptcha-v3.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (ng-recaptcha) which declares RecaptchaV3Module has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
    
    1 export declare class RecaptchaV3Module {
                           ~~~~~~~~~~~~~~~~~
    src/app/app.module.ts:41:14 - error NG6002: Appears in the NgModule.imports of AppServerModule, but itself has errors

**Comment by castevinz** [comment]
How can I help to fix this module import in an angular 9 codebase with Ivy activated ?
Thx in advance ;)

**Comment by castevinz** [comment]
When I drop "forRoot" on RecaptchaModule import, it's working with Ivy !
https://github.com/DethAriel/ng-recaptcha/commit/7fb97fb04049dd058a2394ecef297dac7c6104d1

**Comment by samudiogo** [comment]
For some reason, even removing "forRoot" I got a new error: 

> ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AuthModule)[RecaptchaComponent -> RecaptchaComponent -> RecaptchaComponent -> RecaptchaComponent]: 
  NullInjectorError: No provider for RecaptchaComponent!
NullInjectorError: R3InjectorError(AuthModule)[RecaptchaComponent -> RecaptchaComponent -> RecaptchaComponent -> RecaptchaComponent]: 
  NullInjectorError: No provider for RecaptchaComponent!

But if I set enableIvy to false, works fine only for Recaptcha, but raise errors with components compiled with Ivy

tsconfig.json:
`"angularCompilerOptions": {
    "enableIvy": true
  }`

**Comment by avinashroy** [comment]
I just killed the dev server and started again and it worked. I had faced the same issue with other library and did the same 👍

**Comment by DethAriel** [comment]
Hey folks!

`ng-recapthca` has been updated. v6.0.0 contains changes to make declared package dependency versions compatible with Angular 9 and Angular 10. I'm sorry it took so long to do this, but I hope this comes as good news to you 😀 Please do submit bug reports if you find any (hopefully not, though).

Cheers!

**Comment by sysmat** [comment]
> Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
> 
> ng-recaptcha [es2015/esm2015] (git+https://github.com/DethAriel/ng-recaptcha.git)
> 
> Encourage the library authors to publish an Ivy distribution.
> 

ng13

**Comment by mbuku** [comment]
Hi 
Any help please. i try to import ng-recaptcha but i find the issue below:

'ReCaptchaV3Service' does not appear to be an NgModule class.(-996002)
recaptcha-v3.service.d.ts(23, 28): This likely means that the library (ng-recaptcha) which declares ReCaptchaV3Service is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

i use angular 17, node 20.0.x, npm 10.0.x

thanks for your help in advance!

**Comment by DethAriel** [comment]
@mbuku feel free to open a new issue. Please also specify the version of `ng-recaptcha`
