### ISSUE TITLE
Invisible reCAPTCHA - grecaptcha-badge element is added automatically

### ISSUE THREAD

**Issue by diegomrivero** [DethAriel/ng-recaptcha#169]
I have an application which uses the invisible reCAPTCHA functionality but I just can't get it to work. Looking at the documentation and examples, I see that the implementation is diferent.

I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [X] question / support request
- [ ] other

The documentation states the following regarding the use of the invisible reCAPTCHA:

> Working with invisible reCAPTCHA is almost the same as with regular one. First, you need to provide the right size:

<re-captcha size="invisible" ...></re-captcha>

When I tried to follow this step, the application broke stating that there is already a re-captcha element declared. Looking inside the Angular application code, I don't see any re-captcha element being declared or in typescript, so I am assuming that the element is created during runtime.

The element rendered looks somehow like this:

`<div class="grecaptcha-badge" data-style="bottomright">...</div>`

On the other side, I am injecting the providers in the app module as following:

`{ provide: RECAPTCHA_V3_SITE_KEY, useValue: 'myKey' },
    {
      provide: RECAPTCHA_SETTINGS,
      useValue: {
        siteKey: 'myKey',
      } as RecaptchaSettings,
    },`

Since I haven't done the application, I am little lost here, so that is why I am looking guidance on the documentation, but the code differs a lot.

Please if you could give some guidance on which configurations I am missing.

**Comment by msrumon** [comment]
@diegomrivero, you can absolutely use reCAPTCHA v2 module and component w/ v3 key, as documented [here](https://developers.google.com/recaptcha/docs/faq#can-i-run-recaptcha-v2-and-v3-on-the-same-page).

**Module:**
```ts
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';

import {
  RecaptchaModule,
  RECAPTCHA_SETTINGS,
  RecaptchaSettings,
} from 'ng-recaptcha';
import { environment } from 'src/environments/environment';

import { ContactComponent } from './contact.component';

@NgModule({
  declarations: [ContactComponent],
  imports: [
    CommonModule,
    FormsModule,
    HttpClientModule,
    RecaptchaModule,
  ],
  providers: [
    {
      provide: RECAPTCHA_SETTINGS,
      useValue: {
        siteKey: environment.reCAPTCHA,
        badge: 'inline',
        size: 'invisible',
      } as RecaptchaSettings,
    },
  ],
})
export class ContactModule {}
```

**Component:**
```ts
import { Component, OnInit } from '@angular/core';
import { NgForm } from '@angular/forms';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';

import { environment } from 'src/environments/environment';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.scss'],
})
export class ContactComponent implements OnInit {
  constructor(private readonly httpClient: HttpClient) {}

  ngOnInit() {
    this.httpClient
      .get<ResponseCSRF>(`${environment.api}/api/contact`)
      .subscribe((obs) => {
        console.log(obs);
      });
  }

  onCaptchaResolved(response: string) {
    console.log(response);
  }
```

**Template:**
```html
<main>
  <form>
    <div>
      <re-captcha (resolved)="onCaptchaResolved($event)"></re-captcha>
    </div>
  </form>
</main>
```

**Comment by DethAriel** [comment]
hi @diegomrivero ! Did the suggestion from [this comment](https://github.com/DethAriel/ng-recaptcha/issues/169#issuecomment-661845927) help resolve your issue?

**Comment by DethAriel** [comment]
@diegomrivero grecaptcha badge is supposed to be shown at all times _by default_. There's also this section in [reCAPTCHA FAQ](https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed), which describes how exactly are you allowed to hide the badge, let me include the excerpt here for convenience:

> You are allowed to hide the badge as long as you include the reCAPTCHA branding visibly in the user flow. Please include the following text:
>
> ```
>  This site is protected by reCAPTCHA and the Google
>    <a href="https://policies.google.com/privacy">Privacy Policy</a> and
>    <a href="https://policies.google.com/terms">Terms of Service</a> apply.
> ```
>
> **Note**: if you choose to hide the badge, please use
> 
> ```
> .grecaptcha-badge { visibility: hidden; }
> ```

With that said, if there's still `ng-recaptcha` behavior you feel is worth discussing, please feel free to open a new issue

**Comment by kuncevic** [comment]
@DethAriel it would be great to put the details how to hide the captcha to the readme, otherwise it was taking a bit of time getting there 🤪 ref: https://github.com/DethAriel/ng-recaptcha/issues/169#issuecomment-691842728
