### ISSUE TITLE
Dismiss Recaptcha not triggering an event

### ISSUE THREAD

**Issue by cacothi** [DethAriel/ng-recaptcha#171]
### Summary

I'm submitting a: 
- [ X] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description

When the recaptcha opens, and you click on the backdrop, the recaptcha closes but it doesn't trigger any event that the recaptcha was closed.

This issue affect my user experience, as I disable the submit button when the user press, but when the recaptcha is dismissed I cannot capture the event to enable the button again.

**Comment by DethAriel** [comment]
Hi @cacothi !

Unfortunately, reCAPTCHA does not expose an event for this (as witnessed by the [docs](https://developers.google.com/recaptcha/docs/display)). And since `ng-recaptcha` is just a wrapper around the core lib, I'm afraid there's nothing I can do.
