### ISSUE TITLE
reCaptcha v3 - Is the score always 0.9?

### ISSUE THREAD

**Issue by moritzlillebyzisson** [DethAriel/ng-recaptcha#173]
### Summary

I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [x] question / support request
- [ ] other

### Description
I and my colleague have implemented a mix of v2 and v3, which works, but the score concerns me.
I have read several places, for instance [googleRcaptcha_issue_1](https://github.com/google/recaptcha/issues/345) and [googleRcaptcha_issue_2](https://github.com/google/recaptcha/issues/235) that there is an issue with the score. That it always returns 0.9 regardless if the interaction is done by human or bot.

I don't want to put this in production if there is a problem with the npm package.
There shouldn't be any issues mixing v2 and v3.  As stated in the FAQ on 
[developers.google.com/recaptcha](https://developers.google.com/recaptcha/docs/faq?fbclid=IwAR0JeiXgCmEuzCTU4wO62tmEousF3NCzXwiJ2xMM1QnxO-H0E9Fr-Ip6AHE#can-i-run-recaptcha-v2-and-v3-on-the-same-pagel)

![image](https://user-images.githubusercontent.com/39984300/84520814-68d42800-acd4-11ea-9c84-20fe627f3fbb.png)

Lib versions:

* ng-recaptcha: 5.0.0
* Angular: ^8.2.14
* Typescript :3.5.3

**Comment by eliyahuKriel** [comment]
same problem! how could it be?!

**Comment by DethAriel** [comment]
hey folks!

Scoring algorithm is not part of `ng-recaptcha`, it is not affiliated with Google-provided service at all.

Unfortunately, there's nothing from a lib perspective that I can do about this
