### ISSUE TITLE
Cannot catchError because of uncaught promise

### ISSUE THREAD

**Issue by jsonsystems** [DethAriel/ng-recaptcha#175]
### Summary

An uncaught promise prevents the use of rxjs catchError catching the error if something goes wrong.

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description
If there is a problem with the recaptcha service, an uncaught promise results in an unreocverable error. 

```
zone.js:693 Error: Uncaught (in promise): [object Null]
    at resolvePromise (zone.js:832)
    at resolvePromise (zone.js:784)
    at zone.js:894
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:507)
    at invokeTask (zone.js:1671)
    at MessagePort.globalZoneAwareCallback (zone.js:1697)
```

The problematic function is

```typescript
    ReCaptchaV3Service.prototype.executeActionWithSubject = function (action, subject) {
        var _this = this;
        this.zone.runOutsideAngular(function () {
            // tslint:disable-next-line:no-any
            _this.grecaptcha.execute(_this.siteKey, { action: action }).then(function (token) {
                _this.zone.run(function () {
                    subject.next(token);
                    subject.complete();
                    if (_this.onExecuteSubject) {
                        _this.onExecuteSubject.next({ action: action, token: token });
                    }
                });
            });
        });
    };
```

To reproduce this error, unregister any domains in the racaptcha console, and then call `recaptchaV3Service.execute`. In my case I simply unregistered `localhost` and then tested from `localhost:4200`. 

```
this.recaptchaV3Service.execute('login').pipe(
   catchError((err) => {
      // This is never reached even though an error occurs!
  });
```

Lib versions:

* ng-recaptcha: 5.0.0
* Angular: 9.1.6
* Typescript (`tsc --version`): 3.7.5

**Comment by Lino-LP** [comment]
I'm having the same issue exactly.

Similarly, I haven't found a way to catch an incorrect site key on this line:
`this.recaptchaV3Service.execute('register').subscribe((token) => this.doSomething(token), (error) => { /* this is never reached */ });`

**Comment by Lino-LP** [comment]
Hi @DethAriel 
Thank you for looking into this.
I just installed v6.0.2 and unfortunately I'm seeing the same issue.

To reproduce the issue, simply use an incorrect RECAPTCHA_V3_SITE_KEY

Then in a controller, use this code
`this.recaptchaV3Service.execute('register').subscribe((token) => this.doSomething(token), (error) => { /* this is never reached */ });`

The browser console displays the following message, and my error block is not called:

> Error: Uncaught (in promise): Error: Invalid site key or not loaded in api.js: incorrect-key
> Error: Invalid site key or not loaded in api.js: incorrect-key
>     at Array.<anonymous> (recaptcha__en.js:170)
>     at recaptcha__en.js:162
>     at ng-recaptcha.js:302
>     at ZoneDelegate.invoke (zone-evergreen.js:364)
>     at Zone.run (zone-evergreen.js:123)
>     at NgZone.runOutsideAngular (core.js:41670)
>     at ReCaptchaV3Service.executeActionWithSubject (ng-recaptcha.js:300)
>     at ReCaptchaV3Service.execute (ng-recaptcha.js:293)
