### ISSUE TITLE
Question: Using globally

### ISSUE THREAD

**Issue by pairmix** [DethAriel/ng-recaptcha#176]
I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [x ] question / support request
- [ ] other

Can i use this module globall ie:

1- call Google once into AppComponent
2- save results into store
3- forward results (token) into each axios request (post) via interceptor

Regards

**Comment by DethAriel** [comment]
hi @pairmix ! Each reCAPTCHA token is single-use. This is core reCAPTCHA functionality, and modifying it is, unfortunately, outside of this lib's control. I'd suggest you to check out [reCAPTCHA Developer's Guide](https://developers.google.com/recaptcha/intro) to learn more about this
