### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by Mrgove10** [DethAriel/ng-recaptcha#177]
### Summary
Support angular 10 

I'm submitting a: 
- [ ] bug report
- [x] feature request
- [ ] question / support request
- [ ] other

### Description
Is there any plan to support angular 10 ?

**Comment by pairmix** [comment]
Last update 15 months ago.

https://github.com/LCGroupIT/angular-recaptcha3 or
https://github.com/armenstepanyan/ng-recaptcha3 are Angular 10 compatible.

**Comment by Sampath-Lokuge** [comment]
Yes, This Libray doesn't work. It shows this error:

  Package "ng-recaptcha" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0 || ^7.0.0 || ^8.0.0" (extended), would install "10.0.12").
× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "C:\Users\Sampath\AppData\Local\Temp\ng-e3FunJ\angular-errors.log" for further details.

**Comment by Sampath-Lokuge** [comment]
@pairmix There is an issue in one of the library where you have mentioned. Do you have any feedback here?  https://github.com/LCGroupIT/angular-recaptcha3/issues/1

**Comment by danieldanielecki** [comment]
> Last update 15 months ago.
> 
> https://github.com/LCGroupIT/angular-recaptcha3 or
> https://github.com/armenstepanyan/ng-recaptcha3 are Angular 10 compatible.

Can confirm, just updated from `Angular` **8** to **10** and it's working. Was having this kind of errors on `ng-captcha` **4.2.1** before doing so: 

* `TypeError: Cannot read property 'id' of undefined corejs NgModuleFactory` (in browser's console)
* `core.js:4197 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'id' of undefined TypeError: Cannot read property 'id' of undefined subscriber` (in browser's console)
* `RecaptchaFormsModule has not been processed correctly by ngcc` (Terminal)

Remember that `ng-recaptcha/forms` doesn't exists anymore, import all modules such as `RecaptchaFormsModule` from `ng-recaptcha` when upgrading.

**Comment by DethAriel** [comment]
Hi folks! Sorry for going silent on you, my bad.

I wanted to let you know that this is currently in the works, and there should be a version of `ng-recaptcha` lib with Angular v9 & v10 support in the next couple of days. Thank you for your patience, and please bear with me on this.

Happy coding, y'all!

**Comment by DethAriel** [comment]
Hey folks!

`ng-recaptcha` has been updated. v6.0.0 contains changes to make declared package dependency versions compatible with Angular 9 and Angular 10. I'm sorry it took so long to do this, but I hope this comes as good news to you 😀 Please do submit bug reports if you find any (hopefully not, though).

Cheers!
