### ISSUE TITLE
Is posible to change recatpcha v3 theme with ng-recaptcha?

### ISSUE THREAD

**Issue by juandrn** [DethAriel/ng-recaptcha#181]
### Summary

I'm submitting a:
- [ ] bug report
- [ ] feature request
- [x] question / support request
- [ ] other

### Description
Is posible to change recatpcha v3 theme with ng-recaptcha?

**Comment by Rhonln** [comment]
were you able to solve this?

**Comment by juandrn** [comment]
@Rhonln nou =/

**Comment by DethAriel** [comment]
Hello @juandrn !

[Recaptcha V3 documentation](https://developers.google.com/recaptcha/docs/v3) does not mention such a possibility unfortunately, so I'm afraid we'll have to wait for the core lib to support it before this functionality can be added to `ng-recaptcha`
