### ISSUE TITLE
Change language of recaptcha on language change

### ISSUE THREAD

**Issue by gsinghkular** [DethAriel/ng-recaptcha#183]
I am using the invisible recpatcha v2 with this package, and I see that it gives the option to load recaptcha with different language. But how can I make it load in other language after the user changes the locale on the page without doing a page reload and passing it the locale?

**Comment by DethAriel** [comment]
Hi @gsinghkular, and thank you for taking the time to reach out!

This request has been discussed in #121 . Unfortunately, there's no public grecaptcha API to do that, so the current stance is to not have this fixed
