### ISSUE TITLE
v2 invisible click outside of image box does not resolve

### ISSUE THREAD

**Issue by fbarnard** [DethAriel/ng-recaptcha#184]
### Summary

I'm submitting a: 
- [ ] bug report
- [X] feature request
- [ ] question / support request
- [ ] other

### Description
Call execute the modal with images show and then you click outside of that image box it disappears but the resolve does not get called.

Lib versions:

* ng-recaptcha: 5.0
* Angular: 7
* Typescript (`tsc --version`): 3.97

**Comment by DethAriel** [comment]
Hi @fbarnard !

Can you provide a demo which reproduces the problem?

As a side note, if `grecaptcha` itself is susceptible to this issue, then I'm afraid I cannot help resolve this, as `grecaptcha` core functionality is outside the scope of this library.
