### ISSUE TITLE
ng-recaptcha is not responsive.

### ISSUE THREAD

**Issue by mrsants** [DethAriel/ng-recaptcha#185]
I'm submitting a: 
- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

 When implementing ng-recaptcha on my mobile and it doesn't have a responsive layout, I had to insert styles to correct this behavior, I think it shouldn't be necessary

### Demo
![Captura de Tela 2020-08-25 às 17 53 11](https://user-images.githubusercontent.com/59406899/91226815-ecaa8780-e6fb-11ea-8874-502033d4808c.png)

Lib versions:

* ng-recaptcha: "^5.0.0",
* Angular: 9.0.4
* Typescript (`tsc --version`): 3.8.3

**Comment by danieldanielecki** [comment]
Couldn't reproduce this

**Comment by mrsants** [comment]
> Couldn't reproduce this

aparentemente esse é um problema comum no recaptcha, encontramos uma solução e já está em produção, não sei se o ng-recatcha seria o responsável por corrigir isso, acabei fechando a demanda

[No CAPTCHA reCAPTCHA Resizing](https://stackoverflow.com/questions/28594842/no-captcha-recaptcha-resizing)

**Comment by danieldanielecki** [comment]
I've tried this on my project and haven't noticed the issue. If that's still the case in your app, or simply you can reproduce this I'd advise to provide CodeSandbox and reopen this issue.
