### ISSUE TITLE
Can't set size of badge when using recaptcha v3

### ISSUE THREAD

**Issue by Rhonln** [DethAriel/ng-recaptcha#186]
### Summary

I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [x] question / support request
- [ ] other

### Description
I can't find a way to change the size of the badge when using recaptcha v3. I've tried to use "provide: RECAPTCHA_SETTINGS" to set it globally but it's not working.

**Comment by DethAriel** [comment]
Hi @Rhonln , and thanks for submitting this!

Unfortunately, I do not see the ability to control badge size with recaptcha v3 (as per [docs](https://developers.google.com/recaptcha/docs/v3) at least), so I'm not sure what you are referring to, can you elaborate?
