### ISSUE TITLE
Resolved Function Call Twice After Each Form Submit

### ISSUE THREAD

**Issue by amirzenoozi** [DethAriel/ng-recaptcha#195]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [ ] question / support request 
- [ ] other

### Description
I use ng-recaptcha for some angular form but after each form submit my resoled function call twice and I don't know why, I put my code below:

```typescript

@ViewChild('captchaRef') captchaRef: RecaptchaComponent;

  executeReCaptcha() {
      this.captchaRef.execute(); // Run Once
  }

  resolved(loginForm: any, captchaResponse: string) {
    console.log('Clicked!!!!'); // Run Twice
    const FormValues: any = loginForm['value'];
    this.UserApi.login( { username: FormValues.username, password: FormValues.password }).subscribe(
      (res: any) => {
        console.log('Noice!!!!!'); // Run Twice
      }, (err: Error) => {
        console.log('Something Went Wrong!');  // Run Twice
      }
    );
  }
```

this is my html template: 

```html
    <div class="page-wrap">
      <form class="form" [formGroup]="LoginForm" (ngSubmit)="executeReCaptcha()">
        <div class="container">
          <div class="row row--form">
            <div class="col-xs-24">
              <input type="text" formControlName="username" />
            </div>
            <div class="col-xs-24">
              <input type="password" formControlName="password" />
            </div>
            <span class="spacer spacer--30px"></span>
            <div class="col-xs-24">
              <button type="submit" class="btn btn--green btn--full" [disabled]="!LoginForm.valid">LogIn</button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
  <re-captcha #captchaRef="reCaptcha" (resolved)="resolved(LoginForm, $event)" size="invisible"></re-captcha>
```

**Comment by EvanSevy** [comment]
@amirzenoozi  I have the same problem.  Have you been able to find a solution?

**Comment by amirzenoozi** [comment]
@EvanSevy I set the loading flag in `executeReCaptcha()` Function and check this flag in `resolved()` function and also you should update this flag in your API function callBack. It works for me

**Comment by DethAriel** [comment]
Hey folks! I've tried to reproduce this issue based on the original code that @amirzenoozi submitted, and I created [this Stackblitz demo](https://stackblitz.com/edit/ng-recaptcha-example-yfmgs6?file=src%2Fapp%2Fapp.component.ts). The behavior that I observe is a single execution of `resolved` callback.  Please advise - is this not what you're observing? Also, what Angular/ng-recaptcha versions are causing this? It would really help if you could use the above example to showcase the undesirable execution path.

**Comment by amirzenoozi** [comment]
@DethAriel I have this issue in `angular/ng-recaptcha` version `5.0.0` I have no idea about the latest version

**Comment by DethAriel** [comment]
@amirzenoozi currently I have no way to reproduce this issue. Can it be that there's something more to your use-case? I'm afraid that without a verifiable way to reproduce this (ideally a Stackblitz demo) there's very little I can do to help you.
