### ISSUE TITLE
Angular Universal/Server-Site Rendering (SSR) no reCAPTCHA

### ISSUE THREAD

**Issue by danieldanielecki** [DethAriel/ng-recaptcha#197]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [x] question / support request 
- [ ] other

### Description
I've seen #34, #75 and [#7a5bc6c](https://github.com/DethAriel/ng-recaptcha/commit/7a5bc6c). However, I think so my problem is a bit different. Whenever I'll try to use reCAPTCHA via ng-recaptcha it works great on `ng serve`/client/browser rendering, but on Angular Universal/Server Side Rendering (SSR) the reCAPTCHA simply disappears. I've tried [make this component global](https://github.com/DethAriel/ng-recaptcha#configuring-the-component-globally-see-in-action) as well as [use the site key directly via <re-captcha>](https://github.com/DethAriel/ng-recaptcha#basic-usage-see-in-action). In both cases the same effect: `ng serve` works great, on SSR the reCAPTCHA disappears (and therefore breaks my form, that's a compulsory step to send an email).

Lib versions:

* ng-recaptcha: 6.0.0
* Angular: 10.1.2
* Typescript (`tsc --version`): 3.9.7

**Comment by DethAriel** [comment]
Hi @danieldanielecki !

Could you please describe in more detail what is the behavior you'd expect a server-side rendered reCAPTCHA to have? How does it break your form exactly?

Conceptually, reCAPTCHA doesn't have any meaning during SSR stage, and it even can't be rendered fully in an SSR environment, since its implementation is `<iframe>`-based.

**Comment by danieldanielecki** [comment]
@DethAriel do you want to say that it's infeasible to render reCAPTCHA on Angular Universal?

I'd be happy to have it in any form, without the semantic inline code/in an iframe, but it simply disappears when rendering on the server. Please check the picture below.

Angular

![Angular](https://user-images.githubusercontent.com/12736263/97775641-ad1c7380-1b62-11eb-8453-9c965c358995.png)

Angular Universal

<img width="692" alt="Angular Universal" src="https://user-images.githubusercontent.com/12736263/97775643-aee63700-1b62-11eb-88a1-defa47578b90.png">

**Comment by danieldanielecki** [comment]
@DethAriel I think I've found the problem, the SSR build shows in the console:

`Refused to load the script 'https://www.google.com/recaptcha/api.js?render=explicit&onload=ng2recaptchaloaded' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback. loadScript | @ | load-script.ts:28`

Did you set up any CSP on that? I've completely removed my one and it's still there, the error comes from the `load-script.ts`, which is defined that way (from source maps):

```
declare global {
  interface Window {
    ng2recaptchaloaded: () => void;
  }
}

export function loadScript(
  renderMode: 'explicit' | string,
  onLoaded: (grecaptcha: ReCaptchaV2.ReCaptcha) => void,
  urlParams: string,
  url?: string,
  nonce?: string,
) {
  window.ng2recaptchaloaded = () => {
    onLoaded(grecaptcha);
  };
  const script = document.createElement('script');
  script.innerHTML = '';
  const baseUrl = url || 'https://www.google.com/recaptcha/api.js';

  script.src = `${baseUrl}?render=${renderMode}&onload=ng2recaptchaloaded${urlParams}`;
  if (nonce) {
    // tslint:disable-next-line:no-any Remove "any" cast once we upgrade Angular to 7 and TypeScript along with it
    (script as any).nonce = nonce;
  }
  script.async = true;
  script.defer = true;
  document.head.appendChild(script);
}
```

`document.head.appendChild(script);` that's the problematic line 28.

**Comment by danieldanielecki** [comment]
That's some [Helmet](https://github.com/helmetjs/helmet) problem apparently, therefore closing.

I've also generated an empty `Angular Universal` project to confirm and it works perfectly, simply commenting out [Helmet](https://github.com/helmetjs/helmet)'s default usage (`expressApp.use(helmet());`) solved the error. I'll edit the post here if will get some more info, just in case anyone would face a similar problem or found this threat through Google.
