### ISSUE TITLE
Angular v11 - Error: The target entry-point "ng-recaptcha" has missing dependencies:

### ISSUE THREAD

**Issue by prabh-62** [DethAriel/ng-recaptcha#198]
### Summary

I'm submitting a:
- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description
ng-recaptcha does not work with Angular v11 RC1.

### Demo

```bash
❯ npx @angular/cli@next new admin-console --strict --routing --style css
❯ cd admin-console
❯ npm install ng-recaptcha --save
```
- Setup V3 reCAPTCHA as per [documentation](https://github.com/DethAriel/ng-recaptcha#recaptcha-v3-usage-see-in-action)
- `❯ npm start` and Angular CLI throws an error
```log
Error: The target entry-point "ng-recaptcha" has missing dependencies:
 - @angular/common
 - @angular/forms
```
<img width="1440" alt="reCAPTCHA_v3" src="https://user-images.githubusercontent.com/13006107/97592071-a3fe9b80-19d6-11eb-9eec-ec535534d310.png">

Lib versions:

* ng-recaptcha: 6.0.2
* Angular: 11.0.0-rc.1
* Typescript (`tsc --version`): 4.0.5

**Comment by crodriguezps** [comment]
why is this closed? Can you share solution?
