### ISSUE TITLE
Cannot recover from a failed network call in V2 execute()

### ISSUE THREAD

**Issue by leewinder** [DethAriel/ng-recaptcha#199]
### Summary

I'm submitting a:
- [ ] bug report
- [X] feature request
- [ ] question / support request
- [ ] other

### Description
If you call `.execute()` using V2 ReCAPTCHA with a disabled or non-existent network connection, there doesn't seem to be any notification to the calling code to allow you to recover.

It would be useful to have the ability to be notified should the Google API call fail for any reason.

* Load a form with your network enabled so ReCAPTCHA initialises correctly
* Disable your network connection
* Call `.execute()`

The console displays the following
`GET https://www.google.com/recaptcha/api.js?render=explicit&onload=ng2recaptchaloaded net::ERR_INTERNET_DISCONNECTED`

And I get the following in-browser dialog
<img width="464" alt="Screenshot 2020-11-14 at 19 08 47" src="https://user-images.githubusercontent.com/1649415/99155107-f9140000-26ac-11eb-9f29-adb503d4d222.png">

However, there doesn't seem to be any return back to the application that the process has finished with an error.

Since we disable the submit button when the user wants to progress (pre calling `.execute()`), we don't get any notification to indicate the process has finished, which would then allow us to re-enable the submit button, hence we end up stuck in a pending state unable to try again.

Granted we _could_ delay the disabling of the submit button until after the ReCAPTCHA, which we'll have to do if we continue to use this, however should there be any delay in getting the response back we really don't want to have to manually handle rejecting any accidental double clicks of the submit button.

I imagine this also happens if there are any other issues in calling Google's API, beyond the lack of a network connection.

Lib versions:
* ng-recaptcha: 6.0.2
* Angular: 10.1.6
* Typescript (`tsc --version`): 3.9.7

**Comment by DethAriel** [comment]
Hi @leewinder ! Thank you for submitting this, I'll issue a fix and publish an updated version in the next couple of days!

**Comment by DethAriel** [comment]
Hello again @leewinder ! The feature you described is now available in `ng-recaptcha@6.1.0`. Please refer to the appropriate [documentation section](https://github.com/DethAriel/ng-recaptcha#example-error-handling) on details on how to take advantage of it, and reach out if you have any questions.

Happy coding!

**Comment by Yusuf007R** [comment]
I'm still having this problem
