### ISSUE TITLE
Calling the execute method provokes incorrect behaviour on IOS

### ISSUE THREAD

**Issue by Rhonln** [DethAriel/ng-recaptcha#200]
### Summary

I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [x ] question / support request 
- [ ] other

### Description

When using the execute method I recieve a token, then I use that token to call a web api. Finally, after the web api response, I send the user to whatsapp with a message. On any android device this works well, the browser asks if I want to open the web version or the app. On IOS the web version is opened by default, with the message on the screen. It has an option to 'Continue to chat' wich opens the dialog to select the web version or the app. However, if I remove the recaptcha call then the behaivour is the same as on android (no message is shown on the whatsapp website and you get the dialog asking to use web version or app inmediately).

Has anyone experienced this problem?

**Comment by DethAriel** [comment]
Hi @Rhonln ! Is this still an issue you're facing? Is there somewhere I can exhibit this behavior (or at least parts of it)? Does this happen with any particular iOS browser, or is this a WebView-specific situation?
