### ISSUE TITLE
Getting reCAPTCHA issue post deployment

### ISSUE THREAD

**Issue by kokilarg** [DethAriel/ng-recaptcha#204]
![image (12)](https://user-images.githubusercontent.com/49519314/100999878-391b2400-3583-11eb-9190-a73ca1f9e7c2.png)

In localhost:4200 (ng serve) I am not getting any kind of error
after the build with --prod, I am getting an error as displayed in the above screenshot...
I just created reCAPTCHA with version V2 ( I am not a robot ) and I have given the domain name clearly.
still, I am facing the above issue it is blocking the entire screen or say I get a blank screen.

please, anyone, suggest to me
thank you...

**Comment by DethAriel** [comment]
Hi @kokilarg ! After un-minifying the stack trace, do you have an exact line in `ng-recaptcha`?
