### ISSUE TITLE
Catch error when "https://www.google.com/recaptcha" cannot be reached

### ISSUE THREAD

**Issue by RegniBlef** [DethAriel/ng-recaptcha#207]
### Summary

I'm submitting a: 
- [X] bug report
- [ ] feature request
- [ ] question / support request 
- [ ] other

### Description

I have improved my CSPs (Content-Security-Policies) on the server and noticed that when the `RecaptchaV3Module` cannot reach the URL "https://www.google.com/recaptcha" due to the `connect-src` property, the error won´t be caught leading to infinite loading in my example (see below).

### Demo
```js
  public async register(credentials: RegisterCredentials): Promise<void> {
    this.loading = true;

    this.recaptcha.execute('register').pipe(take(1)).subscribe((token: string) => {
      this.http.post(this.serverUrl, { token }).pipe(take(1)).subscribe(async result => {
        try {
          console.log(result);
          await this.auth.register(credentials);
          this.loading = false;
        } catch (error) {
          console.error(error);
          this.loading = false;
        }
      }, error => {
        console.error(error);
        this.loading = false;
      });
    }, error => {
      console.error(error);
      this.loading = false;
    });
  }
```

This is the error I get:
``
Refused to connect to 'https://www.google.com/recaptcha/api.js?render=KEY&onload=ng2recaptchaloaded' because it violates the following Content Security Policy directive: "connect-src 'self'".
``

I understand that this doesn´t work, because the `connect-src` is set to `self`. However, I would like to catch the error properly, set the loading to false and show some representative message.

**Comment by DethAriel** [comment]
Hi @RegniBlef ! Can you elaborate on why would you want to catch this issue? It is un-recoverable, so catching it during runtime seems to be providing little to no value. That is -- if you know that CSP has been misconfigured, reCAPTCHA will never work, so what's the point in trying to instantiate it in the first place?

**Comment by RegniBlef** [comment]
My thought behind this was that there could be other reasons the endpoint can´t be reached and I would just like to have an option to catch the error and provide an alternative solution. But maybe it is as you say that the use case isn´t really there.
