### ISSUE TITLE
ERROR in ../node_modules/ng-recaptcha/recaptcha/recaptcha-v3.service.d.ts:55:9 - error TS1086: An accessor cannot be declared in an ambient  context.  55     get onExecute(): Observable<OnExecuteData>;            ~~~~~~~~~ ../node_modules/ng-recaptcha/recaptcha/recaptcha-v3.service.d.ts:56:9 - error TS1086: An accessor cannot be declared in an ambient context.   56     get onExecuteError(): Observable<OnExecuteErrorData>;

### ISSUE THREAD

**Issue by manojasati** [DethAriel/ng-recaptcha#214]
ERROR in ../node_modules/ng-recaptcha/recaptcha/recaptcha-v3.service.d.ts:55:9 - error TS1086: An accessor cannot be declared in an ambient 
context.

55     get onExecute(): Observable<OnExecuteData>;
           ~~~~~~~~~
../node_modules/ng-recaptcha/recaptcha/recaptcha-v3.service.d.ts:56:9 - error TS1086: An accessor cannot be declared in an ambient context. 

56     get onExecuteError(): Observable<OnExecuteErrorData>;

**Comment by DethAriel** [comment]
hi @manojasati ! Given the lack of information here, I'm going to close this issue. If you still have it, though, please free to open a new one and use the provided issue template which helps fill in the blanks, such as:

* When does this error happen?
* What is the version of Angular/TS/ng-recaptcha?
* Running which command yields this?

**Comment by yornel13** [comment]
Same error
im ussing

@angular-devkit/architect         0.803.26
@angular-devkit/build-angular     0.803.26
@angular-devkit/build-optimizer   0.803.26
@angular-devkit/build-webpack     0.803.26
@angular-devkit/core              8.3.26
@angular-devkit/schematics        8.3.26
@angular/cli                      8.3.26
@ngtools/webpack                  8.3.26
@schematics/angular               8.3.26
@schematics/update                0.803.26
rxjs                              6.5.5
typescript                        3.4.5
webpack                           4.39.2

please help me.

**Comment by DethAriel** [comment]
what's the `ng-recaptcha` version @yornel13 ?

**Comment by elsasantos** [comment]
Hello. 
I have de same error when compile the ionic project:

    "@angular-devkit/build-angular": "~0.803.20",
    "@angular/cli": "~8.3.23",
    "@angular/compiler": "~8.2.14",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@ionic/angular-toolkit": "^2.1.1",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
    "cordova-android": "9.0.0",
    "ng-recaptcha": "^7.0.1",

Help!

**Comment by ChauISI** [comment]
Hello,
I'm running cmd ng serve or ng build for my project and got this same error:
![image](https://user-images.githubusercontent.com/23340354/107107415-c6d2f400-67fe-11eb-9996-bd1beeba803e.png)

"dependencies": {
    "@angular/animations": "~8.2.8",
    "@angular/cdk": "^8.0.2",
    "@angular/common": "~8.2.8",
    "@angular/compiler": "~8.2.8",
    "@angular/core": "~8.2.8",
    "@angular/forms": "~8.2.8",
    "@angular/material": "^8.0.2",
    "@angular/platform-browser": "~8.2.8",
    "@angular/platform-browser-dynamic": "~8.2.8",
    "@angular/router": "~8.2.8",
    "@fortawesome/fontawesome-free": "^5.12.1",
    "angular2-useful-swiper": "^8.0.1-beta.1",
    "bootstrap": "^4.3.1",
    "classlist.js": "^1.1.20150312",
    "hammerjs": "^2.0.8",
    "jquery": "^3.4.1",
    "lodash-es": "^4.17.15",
    "ng-recaptcha": "^7.0.1",
    "ngx-qrcode2": "0.0.9",
    "ngx-slick-carousel": "^0.4.7",
    "rxjs": "~6.4.0",
    "slick-carousel": "^1.8.1",
    "swiper": "^5.3.1",
    "tslib": "^1.10.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.9.1"
  },


I noticed after running npm install ng-recaptcha --save, there was a warning:
npm WARN ng-recaptcha@7.0.1 requires a peer of @angular/core@^11.0.0 but none is installed. You must install peer dependencies yourself.

Can you share all the dependencies needed to use recaptcha v3?
Thanks!

**Comment by davicedraz** [comment]
Same issue here!

```
"dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/common": "8.1.2",
    "@angular/core": "8.1.2",
    "@angular/forms": "8.1.2",
    "@angular/platform-browser": "8.1.2",
    "@angular/platform-browser-dynamic": "8.1.2",
    "@angular/router": "8.1.2",
    "@angular/service-worker": "8.1.2",
    "@capacitor/android": "^2.0.0",
    "@capacitor/core": "^2.0.0",
    "@capacitor/ios": "^2.0.0",
    "@ionic-native/badge": "^5.30.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/in-app-browser": "^5.19.1",
    "@ionic-native/onesignal": "^5.22.0",
    "@ionic-native/open-native-settings": "^5.17.1",
    "@ionic-native/sqlite": "^5.31.1",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.7.1",
    "@ng-toolkit/universal": "~7.1.2",
    "@ngxs/store": "^3.5.1",
    "@types/socket.io-client": "^1.4.32",
    "capacitor-secure-storage-plugin": "^0.3.1",
    "cordova-open-native-settings": "1.5.2",
    "cordova-plugin-android-permissions": "^1.0.2",
    "cordova-plugin-appsflyer-sdk": "^4.4.26",
    "cordova-plugin-badge": "^0.8.8",
    "cordova-plugin-inappbrowser": "^3.2.0",
    "cordova-plugin-screen-orientation": "^3.0.2",
    "cordova-sqlite-storage": "^5.1.0",
    "core-js": "2.5.4",
    "es6-promise-plugin": "4.2.2",
    "hammerjs": "^2.0.8",
    "mocha": "5.2.0",
    "mochawesome": "4.1.0",
    "mochawesome-merge": "2.0.1",
    "mochawesome-report-generator": "4.0.1",
    "ng-recaptcha": "^8.0.0",
    "onesignal-cordova-plugin": "2.11.2",
    "rxjs": "6.5.1",
    "socket.io-client": "^2.3.0",
    "subsink": "^1.0.1",
    "tslib": "1.9.0",
    "uuid": "^8.0.0",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "0.801.2",
    "@angular-devkit/build-angular": "^0.803.21",
    "@angular-devkit/core": "8.1.2",
    "@angular-devkit/schematics": "8.1.2",
    "@angular/cli": "8.1.2",
    "@angular/compiler": "8.1.2",
    "@angular/compiler-cli": "8.1.2",
    "@angular/language-service": "8.1.2",
    "@capacitor/cli": "^2.0.0",
    "@ionic/angular-toolkit": "2.1.1",
    "@ionic/lab": "3.1.0",
    "@ngxs/devtools-plugin": "3.5.1",
    "@ngxs/logger-plugin": "3.5.1",
    "@types/jasmine": "3.3.8",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "8.9.4",
    "capacitor-resources": "^2.0.3",
    "codelyzer": "5.0.0",
    "cypress": "5.3.0",
    "gulp": "^4.0.2",
    "gulp-gzip": "^1.4.2",
    "gulp-htmlmin": "^5.0.1",
    "handlebars": "^4.5.0",
    "istanbul-reports": "^3.0.2",
    "jasmine-core": "3.4.0",
    "jasmine-spec-reporter": "4.2.1",
    "jetifier": "^1.6.5",
    "karma": "4.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage-istanbul-reporter": "2.1.1",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "1.4.0",
    "karma-spec-reporter": "0.0.32",
    "lighthouse": "^6.0.0",
    "protractor": "5.4.0",
    "puppeteer": "^3.2.0",
    "tslint": "5.15.0",
    "typescript": "3.4.3",
    "yargs": "^15.3.1"
  },
```
