### ISSUE TITLE
Error when compile the ionic project with ng-recaptcha

### ISSUE THREAD

**Issue by elsasantos** [DethAriel/ng-recaptcha#216]
### Summary

I'm submitting a: 

- [ X] bug report
- [ ] feature request
- [ ] question / support request 
- [ ] other

### Description

When compile the ionic project after apply the ng-recaptcha plugin I have this error:

ERROR in ../node_modules/ng-recaptcha/recaptcha/recaptcha-v3.service.d.ts:55:9 - error TS1086: An accessor cannot be declared in an ambient context. 55 get onExecute(): Observable<OnExecuteData>; ~~~~~~~~~ ../node_modules/ng-recaptcha/recaptcha/recaptcha-v3.service.d.ts:56:9 - error TS1086: An accessor cannot be declared in an ambient context. 56 get onExecuteError(): Observable<OnExecuteErrorData>;

**Comment by akilah007** [comment]
Update Angular version to 9+

**Comment by DethAriel** [comment]
@elsasantos did you resolve the issue? What versions of Angular/ng-recaptcha are you using?

**Comment by akilah007** [comment]
> @elsasantos did you resolve the issue? What versions of Angular/ng-recaptcha are you using?

Update Angular version to 9+. If not worked force `npm i ` fresh installation
