### ISSUE TITLE
Webpack 2.x UglifyJsPlugin breaks with `Unexpected token: punc ()`

### ISSUE THREAD

**Issue by anodynos** [DethAriel/ng-recaptcha#217]
### Summary

I'm submitting a: 

- [x] bug report
- [ ] feature request
- [ ] question / support request 
- [ ] other

### Description

The `webpack.optimize.UglifyJsPlugin` of Webpack 2.x breaks with

  `Unexpected token: punc ()) [../~/ng-recaptcha/fesm2015/ng-recaptcha.js:7,0]`

when it loads the fesm2015 version of ng-captcha that uglify doesnt support ;-(

See https://stackoverflow.com/questions/42375468/uglify-syntaxerror-unexpected-token-punc.

We fix this simply by forcing to use the UMD version of ng-captcha (which works fine), just by deleting

     "module": "fesm2015/ng-recaptcha.js",

hence forcing the module system to use

     "main": "bundles/ng-recaptcha.umd.js"

It's an ugly-ish patch, but _It Just Works (R)_ ;-) 

I wonder if there's a way to make this the default or selectable behaviour. I've already tried importing `ng-recaptcha/bundles/...` but my IDE can't resolve it, so its not viable ATM. 

* ng-recaptcha: 7.0.1
* Angular: 6.1
* Typescript (`tsc --version`): 2.9.2

**Comment by DethAriel** [comment]
Does this happen with ng-recaptcha v6.1.0 (the latest version to support Angular 6.x.x)?
