### ISSUE TITLE
ng-recaptcha with lazy loaded module error: No provider for RecaptchaLoaderService

### ISSUE THREAD

**Issue by manduriomane** [DethAriel/ng-recaptcha#218]
### Summary

I'm submitting a: 

- [ ] bug report
- [ ] feature request
- [x] question / support request 
- [ ] other

### Description

Hi,

I try to using ng-recaptcha inside a lazy loaded module that I load when user click on a button.
In particular, when user click on CONTACT button, my app load ContactModule in which  I'm import RecaptchaModule and RecaptchaFormsModule (in addition to the modules for the modal popup).

this is my **contact.moduel.ts**

```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ContactFormComponent } from './contact-form/contact-form.component';
import { RecaptchaFormsModule, RecaptchaModule } from 'ng-recaptcha';


@NgModule({
  declarations: [
    ContactFormComponent
  ],
  imports: [
    CommonModule,
    FormsModule,
    RecaptchaModule,
    RecaptchaFormsModule
  ],
  exports: [
    ContactFormComponent
  ]
})
export classContactModule {
}
```
This is the service that I use to manually lazy load module:

```
export class LazyLoaderService {
  constructor(private compiler: Compiler, private injector: Injector) { }
  loadModule(path: any) {
    (path() as Promise<NgModuleFactory<any> | Type<any>>)
      .then(elementModuleOrFactory => {
        if (elementModuleOrFactory instanceof NgModuleFactory) {
          // if ViewEngine
          return elementModuleOrFactory;
        } else {
          try {
            // if Ivy
            return this.compiler.compileModuleAsync(elementModuleOrFactory);
          } catch (err) {
            throw err;
          }
        }
      })
      .then(moduleFactory => {
        try {
          const elementModuleRef = moduleFactory.create(this.injector);
          const moduleInstance = elementModuleRef.instance;

          // do something with the module...
        } catch (err) {
          throw err;
        }
      });
  }
}
```
`
But in this way, it doesn't work and I get this error:

![image](https://user-images.githubusercontent.com/25469100/115246369-1d757c00-a126-11eb-8eaa-5c8de8416745.png)

How I can fix it?

thanks

**Comment by DethAriel** [comment]
Hi @manduriomane ! Thank you for taking the time to submit the issue. Are you still experiencing it? If so, can you please provide some more info:

* what is the `ng-recaptcha` version?
* what is the Angular version?
* On top of that, it would be much easier for me to assist you if you could provide a reproduction scenario that I could refer to, preferably in the form of a Stackblitz demo. You can fork from [this one](https://stackblitz.com/edit/ng-recaptcha-example) as a starting point
