### ISSUE TITLE
README.md still refers to <recaptcha instead of <re-captcha

### ISSUE THREAD

**Issue by jaykhimani** [DethAriel/ng-recaptcha#22]
Under README.md for the section "[Usage with required in forms](https://github.com/DethAriel/ng-recaptcha/#usage-with-required-in-forms-see-in-action)", example given still uses &lt;recpatcha> instead of &lt;re-captcha>.

**Comment by jaykhimani** [comment]
Wrongly created issue. Closing it

**Comment by DethAriel** [comment]
No worries; this has been a bug indeed :)

**Comment by jaykhimani** [comment]
Ahh... I thought I saw it but when I logged in to raise the issue, somehow I didnt see it. So it must by my browser cache. :)

**Comment by DethAriel** [comment]
That must have been exactly what happened. Anyway, thx for letting me know
