### ISSUE TITLE
Question: Webpack sample

### ISSUE THREAD

**Issue by SMRockend** [DethAriel/ng-recaptcha#23]
I was wondering if someone could point to webpack sample somewhere! I cannot get it up and running in webpack 2.

**Comment by DethAriel** [comment]
Hello! What issue exactly are you running into when using webpack? A normal `npm install` followed by `import { RecaptchaModule } from 'ng-recaptcha'` works for me

**Comment by SMRockend** [comment]
Thanks mate . problem solved. I was using <re-captcha> tag from readme file but looks like the correct one is <recaptcha> without dash.
