### ISSUE TITLE
unit testing in recaptcha v3

### ISSUE THREAD

**Issue by bonomiandreia** [DethAriel/ng-recaptcha#231]
### Summary
hey people, I have a problem with unit testing for recaptcha. I'll explain: 
my subscribe: 
```
this.reCaptchaV3Service
                .execute('key')
                .subscribe(
                     ...
                    error => {
                       ...
                    },
                );
```
in my spec: 
```
{
                    provide: ReCaptchaV3Service,
                    useValue: {
                        execute: () => of('test')
                    }
                },

```

But when I tried use in:
`const test = spyOn(ReCaptchaV3Service, 'execute').and.callThrough();`
I get this error: 
`Argument of type '"execute"' is not assignable to parameter of type '"prototype" | "ɵfac" | "ɵprov"'.`

How can I test / mock this subscribe? 
Thanks :) 

I'm submitting a: 

- [ ] bug report
- [ ] feature request
- [x] question / support request 
- [ ] other

### Description

Lib versions:

* ng-recaptcha:7.0.1
* Angular: 12.1.0
* Typescript (`tsc --version`): 4.3.2

**Comment by DethAriel** [comment]
Did you try doing this:

```
const test = spyOn(ReCaptchaV3Service.prototype, 'execute').and.callThrough();
//                                   ^^^^^^^^^^     
```
?
