### ISSUE TITLE
Support of plugin for Angular v12.1.1

### ISSUE THREAD

**Issue by Solat-Ali** [DethAriel/ng-recaptcha#232]
### Summary

I'm submitting a: question/feature request/bug

### Description

I was upgrading my local Angular application's version from 11.2.2 to latest 12.1.1, but I'm getting the following error: 

![image](https://user-images.githubusercontent.com/52134925/125174714-db1d8180-e1e0-11eb-9be0-6ffa5225c4f5.png)

Please advise? Does ng-recaptcha support Angular 12.1.1 yet? Or am I doing something wrong here? 

Waiting for an answer, thanks!

**Comment by DethAriel** [comment]
Angular 12 support was added in v8.0.0, so this error should be gone after you upgrade the lib
