### ISSUE TITLE
reCAPTCHA v3 execute always returns null

### ISSUE THREAD

**Issue by LucFauvel** [DethAriel/ng-recaptcha#233]
### Summary

I'm submitting a: 

- [x] bug report
- [ ] feature request
- [ ] question / support request 
- [ ] other

### Description
Finally decided to add reCAPTCHAv3 to our page and for some reason the execute token is always null no matter what we do. What makes me think that the issue is with the library is that I can see the successful "userverify" call being made to google and I can see the token just fine in the response.

```
this.recaptchaService.execute('register').pipe(
      takeUntil(this.unsubscribe$)
    ).subscribe((token) => {
      console.log(token);
      this.registerModel.recaptchaV3Token = token;
      this.register();
    }, (error) => {
      this.onCaptchaError(error);
    });
```

Added a console.log for visibility and it just prints null. There are no errors caught by the error handler.
I assume the site key is applied correctly since the call is being made to google with no issue

in any case, here's the module with the site key being applied 
```
const siteKeyFactory = (config: ConfigurationsService) => {
  return config.configurations.g_recaptcha_v3_key;
};

@NgModule({
  declarations: [
    RegisterHomeComponent,
    RegisterComponent,
    RegisterSuccessComponent
  ],
    imports: [
        CommonModule,
        RegisterRoutingModule,
        SharedModule,
        PasswordStrengthMeterModule,
        RecaptchaV3Module,
    ],
  providers: [
    QueryParamService,
    {
      provide: RECAPTCHA_V3_SITE_KEY,
      useFactory: siteKeyFactory,
      deps: [ConfigurationsService]
    }
  ]
})
```

![Screen Shot 2021-07-20 at 2 33 41 PM](https://user-images.githubusercontent.com/14126802/126377235-47dd35a8-5767-4c26-919a-a47d7f97bbff.png)

Lib versions:

* ng-recaptcha: 8.0.0
* Angular: 12.1.2
* Typescript (`tsc --version`): 4.3.5

**Comment by DethAriel** [comment]
Hey! How does the `this.unsubscribe$` look like? v3 resolution might take a while at times.
Also, please double-check that you're providing reCAPTCHA v3 key (not v2!) as `RECAPTCHA_V3_SITE_KEY` token.

Also, it would really help if you could provide a reproduction scenario. You could use the [Stackblitz demo](https://stackblitz.com/edit/ng-recaptcha-example) as a starting point

**Comment by LucFauvel** [comment]
> Hey! How does the `this.unsubscribe$` look like? v3 resolution might take a while at times.
> Also, please double-check that you're providing reCAPTCHA v3 key (not v2!) as `RECAPTCHA_V3_SITE_KEY` token.
> 
> Also, it would really help if you could provide a reproduction scenario. You could use the [Stackblitz demo](https://stackblitz.com/edit/ng-recaptcha-example) as a starting point

Its probably the token, I didn't know there was a difference, the unsubscribe is a subject that returns void that we use to remove subscriptions in ngOnDestroy, so that will only affect it when the user goes off the page.

**Comment by DethAriel** [comment]
@LucFauvel got it. I'm gonna close this issue then, but feel free to re-open if that doesn't turn out to be the case.
