### ISSUE TITLE
execute not triggering any action or callback when component is included in multiple modules

### ISSUE THREAD

**Issue by QuotientColt** [DethAriel/ng-recaptcha#239]
### Summary

- [ x] bug report
- [ ] feature request
- [ x] question / support request 
- [ ] other

### Description

I am sorry but i could not build a reproduction application since the Problem probably lies within the module structure. I assume that because its depends in which order i open the components. Still i think its a bug within the library because there is no error thrown and the action does simply not react. No request is sent aswell. Maybe you have any guesses when you look at the code of the execute function in ReCaptchaV3Service. 

My Module structure:

**app-shared.module**
      -declares: login-compoment
**app.module**
      -includes: app-shared-module
      -renders : login-compoment
**home-module**
      -includes: app-shared-module
      -renders : login-compoment

login-compoment: injects: recaptchaV3Service

Lib versions:

* ng-recaptcha: tried both 7 and 8.0.1 
* Angular: tried 11 and 12
* Typescript 4.3.5

**Comment by QuotientColt** [comment]
After i changed the module structure i could not reproduce the issue. 
login-compoment now directly declared in app.module and there for only present in one module
In my opinion still a "bug" in the library. At least there should be thrown an error or an empty token should be triggered as callback

**Comment by DethAriel** [comment]
hi @QuotientColt !

Since you original problem was solved, I will close this issue. If you would like to submit an enhancement request for `ng-recaptcha`, please feel free to open a new issue.

Thanks!
