### ISSUE TITLE
Question:Change Recaptcha Width!

### ISSUE THREAD

**Issue by SMRockend** [DethAriel/ng-recaptcha#24]
Is it possible to change Recaptcha Width? make it responsible.

**Comment by DethAriel** [comment]
Hello! Is your use-case to show recaptcha on mobile? If so, I'd suggest using the `transform` hack from [StackOverflow](http://stackoverflow.com/questions/27691411/change-new-google-recaptcha-width) or [this blog](https://geekgoddess.com/how-to-resize-the-google-nocaptcha-recaptcha/).

I'll be considering incorporating it into the control in future, but your own CSS files might handle it until then
