### ISSUE TITLE
Recaptcha issue when running on prod due to optimizer

### ISSUE THREAD

**Issue by gauravpatni123** [DethAriel/ng-recaptcha#244]
ERROR in ./node_modules/ng-recaptcha/fesm2015/ng-recaptcha.js

2021-10-06T21:37:51.6725543Z Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):

2021-10-06T21:37:51.6725543Z TypeError: Cannot read property 'kind' of undefined

Using below version 

    "typescript": "~3.4.5"
    "@angular/cli": "~8.1.3",
     "@angular/core": "~8.1.3",
    "ng-recaptcha": "~6.1.0",

**Comment by pcsantana** [comment]
Hi @gauravpatni123 ,

Did you find a solution?

Thank you!

**Comment by gauravpatni123** [comment]
@pcsantana yes, the solution is to downgrade your recaptcha version and test in your local by using the same environment file which you have been using in the production environment so that when it goes to prod it should support that. Thanks

**Comment by gauravpatni123** [comment]
By downgrading the recaptcha version it will fix . Closing it. Thanks

**Comment by pcsantana** [comment]
I already use an old version (v6), now I tried with v5 and it worked.
Thanks @gauravpatni123 !

**Comment by gauravpatni123** [comment]
@pcsantana sounds good to me .
