### ISSUE TITLE
Support for Angular 13

### ISSUE THREAD

**Issue by umairhm** [DethAriel/ng-recaptcha#245]
### Summary

I'm submitting a: 

- [ ] bug report
- [x] feature request
- [ ] question / support request 
- [ ] other

### Description

Angular 13 has been released on November 03, 2021. This is to start the discussion on upgrading `ng-recaptcha` to support Angular 13.

Lib versions:

* ng-recaptcha: 8.1.0
* Angular: 13.0.0
* Typescript (`tsc --version`): 4.4.4

**Comment by Solat-Ali** [comment]
+1

**Comment by EvanSevy** [comment]
Is there an ETA on when we might get this support for ng13?

**Comment by umairhm** [comment]
> Is there an ETA on when we might get this support for ng13?

The PR is ready for review and further steps. I hope it gets merged sooner than later.

**Comment by DethAriel** [comment]
Hey folks!

It’s been a long week, but I’ll take a look at this some time Monday.
Thanks for your patience!

**Comment by Christian-Devs** [comment]
Hi.
I am currently trying to use this package but it is giving me the following error when running ng serve:
Error: node_modules/ng-recaptcha/lib/recaptcha-value-accessor.directive.d.ts:17:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

17     static ɵdir: i0.ɵɵDirectiveDeclaration<RecaptchaValueAccessorDirective, "re-captcha[formControlName],re-captcha[formControl],re-captcha[ngModel]", never, {}, {}, never, never, false>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ng-recaptcha/lib/recaptcha.component.d.ts:59:18 - error TS2314: Generic type 'ɵɵComponentDeclaration' requires 7 type argument(s).

59     static ɵcmp: i0.ɵɵComponentDeclaration<RecaptchaComponent, "re-captcha", ["reCaptcha"], { "id": "id"; "siteKey": "siteKey"; "theme": "theme"; "type": "type"; "size": "size"; "tabIndex": "tabIndex"; "badge": "badge"; "errorMode": "errorMode"; }, { "resolved": "resolved"; "error": "error"; }, never, never, false>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m

How do I resolve this issue

**Comment by DethAriel** [comment]
@Christian-Devs please consult the [versions compatibility table](https://github.com/DethAriel/ng-recaptcha/#angular-versions) in the README. If the problem persists, please open a new issue, following the issue template

**Comment by Christian-Devs** [comment]
> @Christian-Devs please consult the [versions compatibility table](https://github.com/DethAriel/ng-recaptcha/#angular-versions) in the README. If the problem persists, please open a new issue, following the issue template

Hi DethAriel.
Thank you, I downgraded to v9.0.0 and it worked fine.
