### ISSUE TITLE
Build errors when adding NgRecaptcha to a custom Angular library

### ISSUE THREAD

**Issue by lpnam0201** [DethAriel/ng-recaptcha#247]
### Summary

I'm submitting a: 

- [X] bug report
- [ ] feature request
- [ ] question / support request 
- [ ] other

### DESCRIPTION
There are build errors when I add ng-recaptcha to an Angular library

### REPRODUCIBLE EXAMPLE

I created a demo:
https://github.com/lpnam0201/ng-recaptcha-into-lib

At the root folder of the project:
cd .\projects\my-lib
Run the command:
npm install
ng build my-lib

The console will display errors (I attached log file here):
[error logs.txt](https://github.com/DethAriel/ng-recaptcha/files/7686239/error.logs.txt)

### LIB
Lib versions:
* ng-recaptcha: 9.0.0
* Angular: 9.1.13
* Typescript (`tsc --version`): 3.7.5

### NOTE
Is it somehow related to this issue ?
https://github.com/georgipeltekov/ngx-file-drop/issues/176
https://github.com/angular/angular/issues/38893#issuecomment-720736077

**Comment by banana-bread** [comment]
+1

**Comment by DethAriel** [comment]
hi @lpnam0201 ! The version of `ng-recaptcha` that you need for Angular 11 support is actually v7.x.x. I hope this will resolve your issue.

Cheers!
