### ISSUE TITLE
The recaptcha badge persists

### ISSUE THREAD

**Issue by migue99angel** [DethAriel/ng-recaptcha#248]
### Summary

I'm submitting a: 

- [ ] bug report
- [ ] feature request
- [x] question / support request 
- [ ] other

### Description

I am building an app using Angular and Ionic. I have implemented a register component using ng-recaptcha, but my problem is the badge persists when the user navigates to another component.

If I go to the register page, I get registered then the app redirects to the login page but the recaptcha badge is still there.

**Comment by alvaromorenomorales** [comment]
Same problem here. Is there a solution?

**Comment by DethAriel** [comment]
Hey folks! You can refer to [this section in the README](https://github.com/DethAriel/ng-recaptcha#hide-recaptcha-badge). Cheers!

**Comment by sapabg** [comment]
Same problem, this is what I found:

ngOnDestroy() {
  const element = document.getElementsByClassName('grecaptcha-badge')[0] as HTMLElement;
  if (element) {
    element.style.visibility = 'hidden';
  }
}
