### ISSUE TITLE
boot.ts ???

### ISSUE THREAD

**Issue by sterichards** [DethAriel/ng-recaptcha#255]
Please tell me more about boot.ts

It is very randomly placed in the docs for V2 without any description/explaination of what it does, why it's there or how I implement it

**Comment by jtakemoto** [comment]
`boot.ts` is probably referencing the name of angular's main file from an old version. I don't know when it changed, but the equivalent file is `main.ts`.

**Comment by DethAriel** [comment]
Hi @sterichards ! As @jtakemoto correctly gathered, this is indeed an artifact of an older Angular file naming convention. In the newer versions of Angular framework this file is now indeed named `main.ts`. Sorry for the confusion 😔 I will update the README shortly
