### ISSUE TITLE
Recaptcha loading from a wrong url

### ISSUE THREAD

**Issue by pgarzina** [DethAriel/ng-recaptcha#258]
### Summary

I'm submitting a: 

- [ ] bug report
- [ ] feature request
- [x] question / support request 
- [ ] other

### Description

Recaptcha is in some cases being requested from from https://www.google.com.x. ...

We have several user accounts that use our platform and issue a request to get recaptcha on a weird URL that is being blocked by our CSP. They are using Managed Chrome, if that provides any context. For pretty much all of our users recaptcha is working fine.

If anyone has an idea on why this would happen it would be much appreciated. Thank you.

Lib versions:
 * `google/recaptcha` version: recaptcha v3
* ng-recaptcha: 8.0.1
* Angular: 12.2.9
* Typescript: 4.3.5

![recaptcha csp](https://user-images.githubusercontent.com/9975332/165462726-b18e1524-a570-423f-9301-335cc0b21b66.png)

**Comment by DethAriel** [comment]
hi @pgarzina ! It does look like the domain name you referenced is incomplete, and, to be honest, I'm not sure what kind of URL rewriting software was used to achieve this.

I can only point you to the [official reCAPTCHA docs on CSP](https://developers.google.com/recaptcha/docs/faq#im-using-content-security-policy-csp-on-my-website.-how-can-i-configure-it-to-work-with-recaptcha) in this case. The `ng-recaptcha` lib does not have such control over where recaptcha is actually loaded. You can try specifying the domain explicitly using the `RECAPTCHA_BASE_URL` token, but, unfortunately, I don't think this will help in your case.
