### ISSUE TITLE
Version Matrix for compatible versions of Angular

### ISSUE THREAD

**Issue by ChadESmith42** [DethAriel/ng-recaptcha#259]
### Summary

I'm submitting a:

- [ ] bug report
- [ ] feature request
- [x] question / support request 
- [ ] other

### Description
I need a version matching matrix with to show which versions of your library are compatible with specific versions of Angular.

**Comment by DethAriel** [comment]
hey @ChadESmith42 ! I heard you, so there you go, it's in [the README](https://github.com/DethAriel/ng-recaptcha#angular-versions) now. It's a compatibility table, not a matrix, but I hope it'll still serve you well.

Cheers!

**Comment by ChadESmith42** [comment]
@DethAriel, much appreciated! Thank you for the quick response.
