### ISSUE TITLE
Auto submit form when validating invisible captcha

### ISSUE THREAD

**Issue by primg** [DethAriel/ng-recaptcha#26]
Hi,

So I don't know if there is a way to do this, but my problem is the following:

I'm using the invisible captcha on my login page. It goes like this 

```
<div class="form-buttons">
        <div [class.enabled]="isValid() && !isPristine()" (click)="onSubmit();" class="submit-button">Login</div>
        <re-captcha [size]="'invisible'" site_key="6Lfz2xsUAAAAABf0KnVEpLdJptBScodnOYpliVPA"></re-captcha>

    </div>
```

And then

```
  @ViewChild(ReCaptchaComponent) captcha: ReCaptchaComponent;


    /**
     * If the form is valid, handle form submission here
     */
    onSubmit() {
        if (this.isValid()) {
            this.captcha.execute();
            let token = this.captcha.getResponse();
            if (token != "")
               this.signIn();
        }
    }
```

So my problem is that when / if the captcha activates, the user validates it, but then has to click on the submit button again.

Would you know a way to submit the form at the captcha validation ?

Thanks in advance :)

**Comment by DethAriel** [comment]
Getting recaptcha response is an asyncronous, non-blocking process. You should use the `resolved` event emitter instead, like this:

```ts
onSubmit() {
  if (this.isValid()) {
    this.captcha.execute();
    this.captcha.resolved.subscribe(
      (token: string) => {
         if (token) this.signIn();
      },
    );
  }
}
```

**Comment by DethAriel** [comment]
@primg does this work for you now?

**Comment by primg** [comment]
It does, thank you very much !
