### ISSUE TITLE
Recaptcha not always loading

### ISSUE THREAD

**Issue by Mashsquare** [DethAriel/ng-recaptcha#265]
### Summary

I'm submitting a: 

- [ x ] bug report
- [ ] feature request
- [ ] question / support request 
- [ ] other

### Description

I am using recaptcha V3, the badge doesn't always load. When it doesn't load I get the "Invalid site key or not loaded in api.js" but is obviously not the case because when it works my request goes through and I console logged the site key which appears to be correct.
It is pretty random, the first time it tends to load but if you refresh it stops doing so. If I open the incognito window, the badge shows more often. I still have not implemented the form logic as first I wanted the Recaptcha part to be fully functional

This is my app.module:

`
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { initializeApp, provideFirebaseApp } from '@angular/fire/app';
import { environment } from '../environments/environment';
import { provideAnalytics, getAnalytics, ScreenTrackingService, UserTrackingService } from '@angular/fire/analytics';
import { provideAuth, getAuth } from '@angular/fire/auth';
import { provideFirestore, getFirestore } from '@angular/fire/firestore';
import { provideFunctions, getFunctions } from '@angular/fire/functions';
import { provideStorage, getStorage } from '@angular/fire/storage';
import { initializeAppCheck, provideAppCheck, ReCaptchaV3Provider } from '@angular/fire/app-check'
import { AppcheckComponent } from './components/appcheck/appcheck.component';
import { HttpClientModule } from '@angular/common/http';
import { FormComponent } from './components/form/form.component';
import { FormsModule } from '@angular/forms';
import { RECAPTCHA_V3_SITE_KEY, RecaptchaV3Module } from "ng-recaptcha"

@NgModule({
  declarations: [
    AppComponent,
    AppcheckComponent,
    FormComponent
  ],
  imports: [
    BrowserModule,
    RecaptchaV3Module,
    AppRoutingModule,
    BrowserAnimationsModule,
    provideFirebaseApp(() => initializeApp(environment.firebase)),
    provideAnalytics(() => getAnalytics()),
    provideAuth(() => getAuth()),
    provideFirestore(() => getFirestore()),
    provideFunctions(() => getFunctions()),
    provideStorage(() => getStorage()),
    provideAppCheck(() =>
      initializeAppCheck(undefined, {
        provider: new ReCaptchaV3Provider(environment.recaptcha3SiteKey),
        isTokenAutoRefreshEnabled: true,

      })
    ),
    HttpClientModule,
    FormsModule

  ],
  providers: [
    ScreenTrackingService, UserTrackingService,
    { provide: RECAPTCHA_V3_SITE_KEY, useValue: environment.recaptcha3SiteKey }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }`

this is my form.component.ts
`import { Component, ElementRef, OnDestroy, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, throwError, EMPTY, Subscription } from 'rxjs';
import { catchError, retry } from 'rxjs/operators';
import { Functions, httpsCallableData } from '@angular/fire/functions';
import { NgForm } from '@angular/forms';
import { ReCaptchaV3Service, RecaptchaModule, RecaptchaFormsModule, OnExecuteData, OnExecuteErrorData, } from 'ng-recaptcha';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'app-form',
  templateUrl: './form.component.html',
  styleUrls: ['./form.component.css']
})
export class FormComponent implements OnInit, OnDestroy {

  constructor(private http: HttpClient, private recaptchaV3Service: ReCaptchaV3Service) { }

  email: string = '';
  name: string = '';
  accept: boolean = false;
  recaptchaSubscription: Subscription = new Subscription();
  actionSubscription: Subscription = new Subscription();
  siteKey: string = environment.recaptcha3SiteKey;
  mytoken: string = '';

  ngOnInit(): void {

  }

  onSubmit(form: NgForm) {

    this.recaptchaSubscription = this.recaptchaV3Service.execute('importantAction')
      .subscribe(
        {
          next: token => {
            this.mytoken = token;
            this.actionSubscription = this.http.post('my_serverless_recaptcha_verifier', { captcha: this.mytoken }, { responseType: 'text' }).subscribe(data => {
              console.log('results from recaptcha', data);
            })

          },
          error: err => console.log(err.message),
          complete: () => console.log('complete')
        }

      )

  }

ngOnDestroy(): void {
  this.recaptchaSubscription.unsubscribe();
  this.actionSubscription.unsubscribe();
}

}
`

this is my form.component.html

`
<head>
  <script async src="https://www.google.com/recaptcha/api.js?render=myRecaptchaSiteKey" ></script>
</head>
<body>
  <div
    class="h-screen grid md:flex justify-center items-center w-full lg:w-1/3 mx-auto space-x-4"
  >
    <form (ngSubmit)="onSubmit(form)" #form="ngForm">
      <div class="w-full mx-auto p-8">
        <div>
          <input
            class="mx-auto"
            type="text"
            placeholder="Your name"
            id="name"
            class="form-control h-12 w-80 border-2 border-gray-400 p-4 mb-8"
            ngModel
            name="name"
            #name="ngModel"
            required
          />
        </div>

        <input
          type="email"
          placeholder="enter your email address"
          id="email"
          class="form-control h-12 w-80 border-2 border-gray-400 p-4"
          ngModel
          name="email"
          #email="ngModel"
          required
          email
        />

        <div class="mt-4">
          <input
            type="checkbox"
            name="accept"
            id="accept"
            [checked]="false"
            class="mr-2 form-control"
            required
            ngModel
            name="accept"
            #accept="ngModel"
          />
          <span class="text-xs"
            >By ticking this box you our terms & conditions.</span
          >
        </div>

        <div class="flex justify-end text-right">
          <input
            type="submit"
            class="form-control mt-4"
            value="submit"
            [disabled]="!form.valid"
            [ngClass]="form.valid ? 'opacity-100' : 'opacity-50'"
          />
        </div>
      </div>
      <div class="h-10 mt-8 p-8">
        <div *ngIf="!name.valid && name.touched">
          We didn't catch your <b>name</b>, please enter it again 😁
        </div>
        <div *ngIf="!email.valid && email.touched">
          What is your <b>email</b>?
        </div>
      </div>
    </form>
  </div>
</body>

`

Lib versions:

* ng-recaptcha: 9
* Angular: 14
* Typescript (`tsc --version`): 4.7.3

**Comment by xinthose** [comment]
In my case, I moved the `ReCaptchaV3Service` from my login component to one of my `injectable` services.  It should load only once in the app, and not each time a user logouts out and comes to the login page again.  Call the public function from your login component when the login form is submitted to get the token.

```typescript
import {
    ReCaptchaV3Service,
} from "ng-recaptcha";

@Injectable({
    providedIn: "root",
})
export class AuthService {

    constructor(
        private recaptchaV3Service: ReCaptchaV3Service,
    ) { }

    public checkGoogleRecaptcha(action: string): Promise<any> {
        return new Promise((resolve, reject) => {
            this.recaptchaV3Service.execute(action).subscribe({
                next: (token: string) => {
                    resolve(token);
                },
                error: (error: any) => {
                    reject(error);
                },
            });
        });
    }
}
```

**Comment by xinthose** [comment]
```typescript
import { Component, OnDestroy } from '@angular/core';

// recaptcha
import { ReCaptchaV3Service } from "ng-recaptcha";

// rxjs
import { Subscription } from "rxjs";

@Component({
    selector: 'app-login',
    templateUrl: './login.component.html',
    styleUrls: ['./login.component.scss'],
    encapsulation: ViewEncapsulation.Emulated,
})
export class LoginComponent implements OnDestroy {
    reCaptchaSub$: Subscription | undefined = undefined;

    constructor(
        private recaptchaV3Service: ReCaptchaV3Service,
    ) { }

    checkGoogleRecaptcha(): Promise<any> {
        return new Promise((resolve, reject) => {
            this.reCaptchaSub$ = this.recaptchaV3Service.execute("login").subscribe({
                next: (token: string) => {
                    resolve(token);
                },
                error: (error: any) => {
                    reject(error);
                }
            });
        });
    }

    ngOnDestroy() {
        if (this.reCaptchaSub$) {
            this.reCaptchaSub$.unsubscribe();
        }
    }
}
```

**Comment by xinthose** [comment]
I was getting this error because I was using `RECAPTCHA_V3_SITE_KEY` and `RecaptchaV3Module` in `app.module.ts` when I should have been using the instructions for [Configuring the component globally](https://github.com/DethAriel/ng-recaptcha#configuring-the-component-globally-see-in-action).

**Comment by Sanafan** [comment]
Wow... after trying for over 2 hours this one solved it. @Mashsquare thank you very much vor sharing this information, all other information was crap!
