### ISSUE TITLE
google recapcha V3 recaptchaSettings not working for angular

### ISSUE THREAD

**Issue by w-firm** [DethAriel/ng-recaptcha#268]
### Summary

I'm submitting a: 

- [X ] bug report
- [ ] feature request
- [X ] question / support request 
- [ ] other

### Description

Angular recaptcha V3 settings not working

![image](https://user-images.githubusercontent.com/50365787/179184000-9879a1cc-360d-46c6-bd76-6ff287f619a4.png)

Lib versions:

* ng-recaptcha: 10.0.0
* Angular: 10+

**Comment by DethAriel** [comment]
@w-firm please consult the [versions compatibility table](https://github.com/DethAriel/ng-recaptcha#angular-versions). If the issue still persists, please let me know what exact version of Angular you're seeing this problem with
