### ISSUE TITLE
How to run examples

### ISSUE THREAD

**Issue by amolv** [DethAriel/ng-recaptcha#27]
After taking pull, how to run sample ?

**Comment by DethAriel** [comment]
You would need to have ruby installed, and also the `bundler` gem. Then cd to `demo/examples` and `npm install`. In `demo/_config.yml` file, uncomment [line 19](https://github.com/DethAriel/ng-recaptcha/blob/master/demo/_config.yml#L19). After that you should be able to run `npm run demo` from the project directory.

I'm sorry this is so non-straightforward, this has been on my plate for some time, but had no time to fix the flow.

**Comment by DethAriel** [comment]
@amolv had these suggestions worked for you?

**Comment by amolv** [comment]
switched to custom integration, maybe try running in weekend.
