### ISSUE TITLE
Angular v15 dependency upgrade

### ISSUE THREAD

**Issue by mineminemine** [DethAriel/ng-recaptcha#275]
### Summary

I'm submitting a: 

- [ ] bug report
- [ ] feature request
- [ ] question / support request 
- [x] other

### Description

Angular was just recently updated to v15 which is currently incompatible with v10 of ng-recaptcha. Would be great if ng-recaptcha gets upgraded as well to support Angular v15.

**Comment by AJHanekom** [comment]
+1 Thanks for raising.
