### ISSUE TITLE
RECAPTCHA_V3_SITE_KEY - Token returns null when loading dynamic key with useFactory

### ISSUE THREAD

**Issue by lana-white** [DethAriel/ng-recaptcha#278]
### Summary

I'm submitting a: 

- [x] bug report

### Description
I have implemented Recaptcha V3, loading the key dynamically from an API request as per instructions in this issue https://github.com/DethAriel/ng-recaptcha/issues/165
I am initialising my site settings with APP_INITIALIZER, which assigns the recaptcha key value to a variable in this service, then I am retrieving this variable in a function when declaring the RECAPTCHA_V3_SITE_KEY in my module.

I cannot spend hours creating a stackblitz example as my project is huge and too hard to explain. When I hard code the key value (useValue) the token is not null and works fine. I cannot declare this key as static (like every single example out there which uses either the key as an environment variable, or just hard codes it).

You would think that there would be an example of it being loaded dynamically!

I have inspected and can see in the DOM, the key is definitely being loaded: 
`https://www.google.com/recaptcha/api.js?render=XXXXXXXXXXX&onload=ng2recaptchaloaded`

And the recaptcha badge is loading on the page, as well as trying to make me "select all houses with chimneys".

### Demo

- [x] I did my best to come up with a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)

App Module:
![image](https://user-images.githubusercontent.com/77252320/203456662-016eb934-6e5b-4579-be63-a548d1d7fc2a.png)

In my component when calling recaptcha after button click:

`
  this.recaptchaV3Service.execute('importantAction').subscribe({
          next: async (token) => {
            console.log(token); // This returns null       
          }
 });
`

In my component on ngOnInit: 
`
    this.recaptchaSubscription = this.recaptchaV3Service.onExecute.subscribe((data: OnExecuteData) => {
      console.log(data); //This prints - {action: 'importantAction', token: null}
    });
`

In my component constructor, I inject the sitekey which prints a value:
`constructor(@Inject(RECAPTCHA_V3_SITE_KEY) public siteKey: string) {
console.log(siteKey); //Prints the key
}`

Lib versions:

* ng-recaptcha: 10.0.0
* Angular: 14.2.8
* Typescript (`tsc --version`): 4.8.4

-->

**Comment by DethAriel** [comment]
Hi! Are you certain that the `getSettings` function is executed? I've tried reproducing this issue, and I can not see the behavior that you described, see for yourself [here](https://stackblitz.com/edit/ng-recaptcha-example-ck6qcd).

If you could adjust the above example in a way that will show the behavior you're describing, I will look further into it.

**Comment by YevanKiev** [comment]
> I'm facing a similar issue, this is likely due to the `ReCaptchaV3Service` service being injected within an imported module, which in turns resolves `RECAPTCHA_V3_SITE_KEY` before `APP_INITIALIZER` has completed.
> 
> Still working on the solution though.


Any news regarding this case?

**Comment by montella1507** [comment]
Same here.

**Comment by montella1507** [comment]
TBH it returns NULL now even with static SITE KEY...

It looks like there is breaking change in Recaptcha script??
<img width="912" alt="image" src="https://github.com/DethAriel/ng-recaptcha/assets/10418323/1fe74788-5e7d-4ca7-964e-6fee66621697">

Token here is NULL... and it is function from recapctha google script.

**Comment by montella1507** [comment]
Funny thing is, it works when i put breakpoint inside google's captcha script... Maybe some kind of race condition?

**Comment by montella1507** [comment]
Ok i am here to say I am sorry it was only miscomunication between me and my collegue... I was using V3 but had token to V2 so it acted strangely... It worked randomly :-) 

Now. I can confirm it works even in standalone API with useFactory.

<img width="290" alt="image" src="https://github.com/DethAriel/ng-recaptcha/assets/10418323/e8785112-9756-43c9-b1cb-fd1b133d6504">

<img width="487" alt="image" src="https://github.com/DethAriel/ng-recaptcha/assets/10418323/1da850e1-38b3-438d-844e-54f8516998f0">

**Comment by DethAriel** [comment]
This works for me, as seen by the fact that the demo site works fine. If you feel like the documentation doesn't address your issue, or if you feel like there's a different problem, please feel free to submit a new issue with a reproducing example.
