### ISSUE TITLE
ng-recaptcha (v 5.0.0) checkbox is getting uncheck after spins for few seconds

### ISSUE THREAD

**Issue by harshgupta007** [DethAriel/ng-recaptcha#285]
### [ng-recaptcha (v 5.0.0) checkbox is getting uncheck after spins for few seconds](https://stackoverflow.com/questions/75623291/ng-recaptcha-v-5-0-0-checkbox-is-getting-uncheck-after-spins-for-few-seconds)

I'm submitting a: 

- [ ] bug report
- [ ] feature request
- [x] question / support request 
- [ ] other

### Description

On click of I'm not a Robot checkbox, it spins for few seconds and then it remains un-checked. (resolved) method is not emmiting anything. Also there's no console error.

Sample code-
`<re-captcha size="normal" 
  formControlName="recaptchaShare" 
  siteKey="{{ reCaptchaKey }}" 
  (resolved)="_verifyToken($event)">
</re-captcha>`

My Observation -  It does not make any network call while click on **I'm not a robot** checkbox. 
From UI we are passing **reCaptchaKey**.
It should probably process the key and returns token but, the ouput event -> **(resolved)** not at all emiting token.

Note: This issue I'm facing only in production as I can't reproduce this in local environment using **siteKey**.

Lib versions:

* ng-recaptcha: "^5.0.0"
* Angular: ~9.1.3
* Typescript (`tsc --version`): ~3.7.5

**Comment by DethAriel** [comment]
Hi @harshgupta007 ! Were you able to reproduce the issue? Without a reproduction, I cannot actually fix the error I'm afraid, so I am force to close this issue. Feel free to open a new one when you're able to come up with a proper repro steps
