### ISSUE TITLE
error  unit test with standalone component

### ISSUE THREAD

**Issue by wfpaisa** [DethAriel/ng-recaptcha#286]
### Summary

I'm submitting a: 

- [ ] bug report
- [ ] feature request
- [x] question / support request 
- [ ] other

### Description

Please could you help me to solve this error, I have used this solution using mudules and it works, but in standalone components it does not work.

```js
let reCaptchaV3Service: jasmine.SpyObj<ReCaptchaV3Service>;

describe('@modules/signin/pages - UserComponent', () => {

const reCaptchaV3ServiceSpy = jasmine.createSpyObj(ReCaptchaV3Service, ['execute']);

beforeEach(async () => {
  await TestBed.configureTestingModule({
  imports: [
          RecaptchaV3Module,
  ],
  providers: [
          { provide: RECAPTCHA_V3_SITE_KEY, useValue: environment.captcha },
          { provide: ReCaptchaV3Service, useValue: reCaptchaV3ServiceSpy },
  ]}).compileComponents();
}

  it('should handle captchaGetToken()', fakeAsync(() => {
    reCaptchaV3Service = TestBed.inject(ReCaptchaV3Service) as jasmine.SpyObj<ReCaptchaV3Service>;
    reCaptchaV3Service.execute.and.returnValue(of('123xxx'));

    component.captchaGetToken();
    tick(10);
    expect(reCaptchaV3Service).toHaveBeenCalled();
  }));
````

<img width="815" alt="image" src="https://user-images.githubusercontent.com/1735752/222929661-34a48d9e-606c-4049-83e9-5dc535404401.png">

Thanks :)

**Comment by DethAriel** [comment]
Hi @wfpaisa ! This seems more like a question around generic `jasmine` mocks setup, and is thus better suited to a site such as StackOverflow
