### ISSUE TITLE
ng-recaptcha _502-gateway issue 

### ISSUE THREAD

**Issue by maniashokkumar** [DethAriel/ng-recaptcha#287]
### 🛑 Hold on for a moment

If this issue does not directly relate to `ng-recaptcha` functionality, then please consider bringing awareness to it in this project: https://github.com/google/recaptcha
![image](https://user-images.githubusercontent.com/92813990/235977230-7be1e7f8-e87b-49af-9495-b11593002386.png)

**Comment by DethAriel** [comment]
This report is not related to `ng-recaptcha`
