### ISSUE TITLE
Angular v16 support

### ISSUE THREAD

**Issue by kuncevic** [DethAriel/ng-recaptcha#288]
### Summary

I'm submitting a: 
- [ x] other

### Description

Angular v16 just got released, this package needs to be updated to support that version

**Comment by arjenbrandenburgh** [comment]
PR opened at #289

**Comment by MarcosPaulo775** [comment]
Has a forecast date for merge ?

**Comment by arjenbrandenburgh** [comment]
I cannot merge it. @DethAriel, do you happen to have time to take a look at the PR and publish a new version?

**Comment by MarcosPaulo775** [comment]
Other PR #290

**Comment by CarlosTorrecillas** [comment]
@DethAriel do you know when will you be able to merge this in? We are in the process of upgrading to Angular 16 and this is a blocker for us. Thanks!

**Comment by arjenbrandenburgh** [comment]
@DethAriel My PR at #289 has been updated and all builds and tests succeed now.

**Comment by AshleyMedway** [comment]
@DethAriel #290 has been updated also. ran all scripts that you mentioned. I did run from contribution.md but I think the prettier one is not there.

I can setup the CI in our Azure DevOps account if you want?

**Comment by Dzivo** [comment]
Do you have any news when this could be finished ? Thanks for the hard work

**Comment by DethAriel** [comment]
Angular 16 support is now available in the `v12.x.y` branch. Happy coding everybody, and huge thx to @AshleyMedway and @arjenbrandenburgh !!
