### ISSUE TITLE
Issue installing on angular 4.0.3

### ISSUE THREAD

**Issue by gal-exelweb** [DethAriel/ng-recaptcha#29]
Trying to use "npm i ng-recaptcha --save"
when importing, i get a 404 error in the console

`
login:18 Error: (SystemJS) XHR error (404 Not Found) loading http://10.0.0.5:3000/ng-recaptcha
	Error: XHR error (404 Not Found) loading http://10.0.0.5:3000/ng-recaptcha
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://10.0.0.5:3000/node_modules/zone.js/dist/zone.js:1230:39) [<root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://10.0.0.5:3000/node_modules/zone.js/dist/zone.js:460:38) [<root>]
	Error loading http://10.0.0.5:3000/ng-recaptcha as "ng-recaptcha" from http://10.0.0.5:3000/app/app.module.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://10.0.0.5:3000/node_modules/zone.js/dist/zone.js:1230:39) [<root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://10.0.0.5:3000/node_modules/zone.js/dist/zone.js:460:38) [<root>]
	Error loading http://10.0.0.5:3000/ng-recaptcha as "ng-recaptcha" from http://10.0.0.5:3000/app/app.module.js`

Tried to set defaultJsExtension to js, no difference...

Tried adding to the map in the systemjs.config.js:
`'ng-recaptcha': 'npm:ng-recaptcha/index.js',`

then i get a different error:
`GET http://10.0.0.5:3000/node_modules/ng-recaptcha/recaptcha/recaptcha.component 404 (Not Found)` for service and module as well :/

Am I missing something basic? red the instructions like 16 times already

**Comment by DethAriel** [comment]
Hi! Could you please tell me your `ng-recaptcha` version and also share the systemjs config file?

**Comment by gal-exelweb** [comment]
Latest 2.0.2 ng-recaptcha,
Latest 4.0.3 angular

Attaching the systemjs.config.js, please be aware that I already removed the 'ng-recaptcha': 'npm:ng-recaptcha/index.js' line

`/**, RecaptchaModule.forRoot()
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      'app': 'app',

      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      'ng2-validation': 'npm:ng2-validation/bundles/ng2-validation.umd.js',
      'ng2-simple-global': 'https://npmcdn.com/ng2-simple-global/lib/simple-global.js',

      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        defaultExtension: 'js',
        meta: {
          './*.js': {
            loader: 'systemjs-angular-loader.js'
          }
        }
      },
      rxjs: {
          defaultExtension: 'js'
      },
      'ng2-custom-validation': {
          defaultExtension: 'js'
      }
    }
  });
})(this);
`

**Comment by DethAriel** [comment]
Try doing it this way (it's how the demos for ng-recaptcha work):

```js
System.config({
  map: {
    /* ... */
    'ng-recaptcha': 'npm:ng-recaptcha',
  },
  packages: {
    /* ... */
    'ng-recaptcha': { main: 'index.js', defaultExtension: 'js' },
  },
});
```

**Comment by DethAriel** [comment]
Please, let me know if the issue you've encountered gets resolved by this

**Comment by gal-exelweb** [comment]
That's awsome!
Works well, I wonder how I missed it...
Might consider adding it to the documentation for easier future integration? :)
