### ISSUE TITLE
Getting accessibility issue using JAWS screen reader when using recaptcha v2 sitekey

### ISSUE THREAD

**Issue by harish-byralingaiah** [DethAriel/ng-recaptcha#291]
Hello Team,

When using tab key in JAWS screen reader recaptcha checkbox is reading the complete IFRAME URL instead of saying checkbox but same is working using arrow keys for navigation. 

 "ng-recaptcha": "^5.0.0"
Angular cli: 14

**Comment by harish-byralingaiah** [comment]
We are using recaptcha V2 site key. Kindly help.

**Comment by harish-byralingaiah** [comment]
We have tried with latest version 10.0.1 compatible with Angular 14, even after the issue persist. Kindly need your immediate response on this as we have production release early next week.

**Comment by DethAriel** [comment]
hi @harish-byralingaiah ! Do you have a proposal on how this issue can be fixed?

**Comment by harish-byralingaiah** [comment]
Hi, I tried to adding a title and aria-label to re-captcha element, but after doing so, it reads the tile and aria-label first, followed by the  Iframe URL. So I am not able to find a solution for this.

**Comment by harish-byralingaiah** [comment]
Hi, can the role="presentation" from the iframe be removed?

**Comment by DethAriel** [comment]
@harish-byralingaiah the iframe parameters are not under the control of `ng-recaptcha`. I would suggest that you consider bringing awareness to this issue in the main recaptcha project: https://github.com/google/recaptcha

Since this issue is not fixable in `ng-recaptcha`, closing this ticket as invalid
