### ISSUE TITLE
What is the recommended way to load recaptcha when site key comes from back-end 

### ISSUE THREAD

**Issue by vorant94** [DethAriel/ng-recaptcha#294]
### Summary

- [x] question / support request

### Description

I have an app, where I decided to avoid storing any api keys (even public ones) in the source code. As a result upon app init I make a request to back-end, that returns me all sorts of api keys that client needs. Your lib provides handy token to configure site key `RECAPTCHA_V3_SITE_KEY`, is there a recommended way to provide this token asynchronously?

**Comment by nbvmvbm43542** [comment]
I'm also looking forward to this functionality

**Comment by vorant94** [comment]
> I'm also looking forward to this functionality

in the end I found a way to load scripts programmatically, here [the gist](https://gist.github.com/vorant94/8767e99e2575fc0c3629920334c33eca) with an example. in case you need only recaptcha v3 you don't actually need a framework specific wrapper, you can call methods right away

p.s. don't forget to add regaptcha types, so the compiler won't complain

**Comment by DethAriel** [comment]
Hi @vorant94 and all!

[This comment](https://github.com/DethAriel/ng-recaptcha/issues/165#issuecomment-885330383) provides a way to achieve the desired outcome in an Angular-idiomatic way. I will also add this to the lib's README for easier findability

**Comment by oi75ukhjguz1trd** [comment]
https://github.com/DethAriel/ng-recaptcha/issues/165#issuecomment-749595052

The comment was completely ignored.
Blank (white) page and backend unavailability !?!
This is workaround, not proper solution.
