### ISSUE TITLE
There is no binding for the data-badge attribute

### ISSUE THREAD

**Issue by misterjojo** [DethAriel/ng-recaptcha#30]
I need to customize de css of my invisible recaptcha but there is no binding property to the data-badge attribute.
According to official invisible recaptcha doc (https://developers.google.com/recaptcha/docs/invisible) , there should be a ReCaptchaV2.Badge enum with the following values : 
"bottomright", "bottomleft", "inline".

**Comment by DethAriel** [comment]
Thanks for submitting this! It indeed needs to be tackled, I'll add support for this once I have time to do this. In the meanwhile, feel free to submit a PR

**Comment by DethAriel** [comment]
Added in v2.1.0

**Comment by Toub** [comment]
Great. Please update the documentation too!

**Comment by DethAriel** [comment]
Good point, @Toub , will do that soon
