### ISSUE TITLE
No way to make v3 invisible

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [DethAriel/ng-recaptcha#302]
I am using recaptcha v3 and everything works fine except that i cannot make it invisible.
1. There is no overload in this.recaptchaV3Service.execute
2. Also adding div as described in google recapture is not working
```
<div class="g-recaptcha" [attr.data-sitekey]="recaptchaKey" data-size="invisible"></div>
```

if i add another re-capture element as mentioned in your docs i get an error saying "recaptcha is already rendered"

Any advice?

**Comment by vorant94** [comment]
i followed [recaptcha faq](https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed) and it worked like a charm...

tl;dr global style of makes the trick
```
.grecaptcha-badge { visibility: hidden; }
```

but according to recaptcha policy we still need to give a credit to them

**Comment by DethAriel** [comment]
Hi @vytautas-pranskunas- ! Apart from this issue being raised multiple times before, there is [a section in the README](https://github.com/DethAriel/ng-recaptcha#hide-recaptcha-badge) on this particular topic. Please consult the library documentation and past issues, as well as reCAPTCHA policies.

Closing this as invalid duplicate.
