### ISSUE TITLE
Add support for Trusted Types

### ISSUE THREAD

**Issue by bjarkler** [DethAriel/ng-recaptcha#304]
### Summary

I'm submitting a: 

- [ ] bug report
- [x] feature request
- [ ] question / support request 
- [ ] other

### Description

[Trusted Types](https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API) is a Content Security Policy feature that allows web application owners to guard against insecure usage of dangerous DOM APIs and prevent Cross-Site Scripting vulnerabilities. The default version of the reCAPTCHA library is not compatible with Trusted Types, but can be made compatible by adding `&trustedtypes=true` as a query parameter when [loading the library](https://github.com/DethAriel/ng-recaptcha/blob/429e440817f17661cbf0417c2c942cab21513558/projects/ng-recaptcha/src/lib/load-script.ts#L21).

Currently applications using ng-recaptcha cannot adopt Trusted Types because it doesn't seem possible to add that query parameter. To fix this I propose either always setting the parameter (there shouldn't be any downsides) or making it configurable as part of the ng-recaptcha interface.

I'd be happy to send a PR implementing this.

**Comment by DethAriel** [comment]
Hello @bjarkler! Thank you for submitting this, as well as providing the relevant documentation and code references!

This does indeed sound like a worthy addition with no visible downsides, so let me make this happen.
