### ISSUE TITLE
Cannot vertically scroll images in recaptcha on mobile popup

### ISSUE THREAD

**Issue by pontusarfwedson** [DethAriel/ng-recaptcha#305]
### Summary

I'm submitting a: 

- [x] bug report
- [ ] feature request
- [ ] question / support request 
- [ ] other

### Description

We use an recaptcha component (v2) on our website and then load that in a WKWebView in our iOS app in order to get recaptcha-validation for our users when registering. We current use ng-recaptcha 4.3.0 (I know this is old).
The WebView appears inside a dialog. Previously we were always able to scroll the recaptcha images up and down to select the correct ones. But now, all of a sudden, the actual images are not scrollable. If you try to scroll you notice that only the background will scroll. 
We have tried to open up the website where we have the component in a browser and make the window smaller. Also there we see this behavior. Scrolling only affects the background.
This have caused users not being able to register because they cannot fulfill the recaptcha challenge.

Lib versions:

* ng-recaptcha: 4.3.0
* Angular: 8
* Typescript (`tsc --version`): __

**Comment by DethAriel** [comment]
Hi @pontusarfwedson ! This issue does not directly relate to `ng-recaptcha`. Please consider bringing awareness to it in this project: https://github.com/google/recaptcha
