### ISSUE TITLE
Can't bind to 'siteKey' since it isn't a known property of 're-captcha'

### ISSUE THREAD

**Issue by ammad172** [DethAriel/ng-recaptcha#306]
In angular 15 i have updated the ng-recaptcha version from 11.0.0 to 12.0.2 and when i ran the porject this error started appearing 

**Can't bind to 'siteKey' since it isn't a known property of 're-captcha'**

While its clearly exists in the library

![image](https://github.com/DethAriel/ng-recaptcha/assets/35794500/485380d8-73ab-4140-8ca6-fef1ee1be2af)

These are my project stats

![image](https://github.com/DethAriel/ng-recaptcha/assets/35794500/a7b6f66a-1797-4f01-93ed-0f3de0da2069)

**Comment by DethAriel** [comment]
Hi @ammad172 ! `ng-recaptcha@12` is incompatible with Angular 15, as per the [compatibility table in README](https://github.com/DethAriel/ng-recaptcha#angular-version-compatibility) as well as [the CHANGELOG](https://github.com/DethAriel/ng-recaptcha/blob/master/CHANGELOG.md#1200-2023-05-24)

**Comment by ammad172** [comment]
> Hi @ammad172 ! `ng-recaptcha@12` is incompatible with Angular 15, as per the [compatibility table in README](https://github.com/DethAriel/ng-recaptcha#angular-version-compatibility) as well as [the CHANGELOG](https://github.com/DethAriel/ng-recaptcha/blob/master/CHANGELOG.md#1200-2023-05-24)

Than how i do suppose to migrate to latest version of Angular if this control wont work in that?

**Comment by DethAriel** [comment]
Please read the compatibility table and the changelog to find a version of ng-reCAPTCHA that is compatible with Angular 15
