### ISSUE TITLE
Feature Request Support for WAF

### ISSUE THREAD

**Issue by Rossco8** [DethAriel/ng-recaptcha#307]
### Feature Request

Is it currently possible to add the `waf=session` paramater?
https://cloud.google.com/recaptcha-enterprise/docs/implement-waf-ca#session-token

If not, it would be great to have this feature. ie. Need the equivalent of
````
<script src="https://www.google.com/recaptcha/enterprise.js?render=SESSION_TOKEN_SITE_KEY&waf=session" async defer></script>
```

**Comment by DethAriel** [comment]
as of `ng-recaptcha@13.2.0`, you can use `RECAPTCHA_LOADER_OPTIONS` param to achieve the desired behavior
