### ISSUE TITLE
Standard Angular Standalone app giving NullInjectionError: R3InjectorError error

### ISSUE THREAD

**Issue by KyleSmith0905** [DethAriel/ng-recaptcha#309]
### Summary

I'm submitting a:

- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description
I have a Angular 16 standalone component using `ng-recaptcha`.

However, I'm getting this error:
```
Uncaught (in promise): NullInjectorError: R3InjectorError(Standalone[SupportPage])[ReCaptchaV3Service -> InjectionToken recaptcha-v3-site-key -> InjectionToken recaptcha-v3-site-key -> InjectionToken recaptcha-v3-site-key]: 
  NullInjectorError: No provider for InjectionToken recaptcha-v3-site-key!
NullInjectorError: R3InjectorError(Standalone[SupportPage])[ReCaptchaV3Service -> InjectionToken recaptcha-v3-site-key -> InjectionToken recaptcha-v3-site-key -> InjectionToken recaptcha-v3-site-key]: 
  NullInjectorError: No provider for InjectionToken recaptcha-v3-site-key!
```

### Demo

- [x] I did my best to come up with a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)

https://stackblitz.com/edit/ng-recaptcha-example-5nzbhq?file=src%2Fapp%2Fapp.component.ts

Lib versions:

* ng-recaptcha: tested 12.0.1 and 12.0.2
* Angular: tested 16.0.2 and 16.2.12
* Typescript (`tsc --version`): 4.0.2

**Comment by MrKioZ** [comment]
I have the same issue
Im using angular 16.2.12

**Comment by DethAriel** [comment]
you have to move the providers appropriately. Check out [this StackOverflow answer](https://stackoverflow.com/a/77163833/2645305), or take a look at the [fixed example](https://stackblitz.com/edit/ng-recaptcha-example-whpssk).
