### ISSUE TITLE
Question about changing the language of the captcha

### ISSUE THREAD

**Issue by JoeTac** [DethAriel/ng-recaptcha#39]
In your example here: https://dethariel.github.io/ng-recaptcha/language

Is there a way to load the current language of the locale being used? 
ie. something like this:
```
import { NgModule, LOCALE_ID } from '@angular/core';
...
providers: [
    {
      provide: RECAPTCHA_LANGUAGE,
      useValue: LOCALE_ID,
    },
```

I am currently using AOT translations for my app if that helps.

Thanks

**Comment by DethAriel** [comment]
@JoeTac as far as I understood, you want to reuse whatever you set in `LOCALE_ID` as `RECAPTCHA_LANGUAGE`, is that right?

**Comment by JoeTac** [comment]
@DethAriel Yes thats exactly right

**Comment by DethAriel** [comment]
@JoeTac you can do this:

```ts
providers: [
  {
    provide: RECAPTCHA_LANGUAGE,
    useExisting: LOCALE_ID,
  },
```

**Comment by JoeTac** [comment]
@DethAriel Perfect! Exactly what I was looking for. Thank you!
