### ISSUE TITLE
An angular variable/constant as sidekey?

### ISSUE THREAD

**Issue by myonara** [DethAriel/ng-recaptcha#45]
I want to use the recaptcha multiple times, test it on my development with a different key as in production environment. In the latest angular 4 project created with angular/cli there is the following code within src/environment/environment.ts:
```
export const environment = {
  production: false,
  recaptcha_sitekey: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI' // site key for testing.
};
```
Later for production there will be another code. My question is: How to use this constant in the sidekey-Parameter of ng-recaptcha? It would be hard to exchange all occurences for production code.

**Comment by DethAriel** [comment]
Hi @myonara !

I'm afraid there is no way to configure this on a global level for now. This will be a great feature, though. I will try and add it in the next couple of weeks, but you are free to submit a PR for it if you want to!

**Comment by myonara** [comment]
Hi @DethAriel ,

thanks for the immediate answer. I will try to get the Recpatcha running with the fixed sitekey and my node.js backend first. So currently I can wait for the enhancement.
