### ISSUE TITLE
ReCaptcha stealing the focus

### ISSUE THREAD

**Issue by SergiusSidorov** [DethAriel/ng-recaptcha#49]
After loading, recaptcha steals the focus from the focused field.
It should be able to override the method Recaptcha.focus_response_field .
Thanks.

**Comment by DethAriel** [comment]
@SergiusSidorov thanks for submitting this issue! Could you also post an example of how you're using `<re-captcha>` along with the element it steals focus from, please?

**Comment by SergiusSidorov** [comment]
I was jumping to conclusions. The focus was intercepted with CodeLive bar (angular ide). Sorry for my mistake.
