### ISSUE TITLE
Having custom transform styles

### ISSUE THREAD

**Issue by erijin** [DethAriel/ng-recaptcha#50]
https://geekgoddess.com/how-to-resize-the-google-nocaptcha-recaptcha/

**Comment by DethAriel** [comment]
Hi! This is a feature that is only viable for mobile users, so I'm not sure how likely it is that I will include it into the lib.
BTW, you can use this style even now, without having it in component

**Comment by erijin** [comment]
@DethAriel How?

**Comment by DethAriel** [comment]
@erijin For example, you can wrap `<re-captcha>` in a `<div>` and apply the `"transform"` styles to that element, as shown in [this plunk](https://plnkr.co/edit/RrsmOLhCVg4tLOqL1XA2?p=preview)
