### ISSUE TITLE
How to get an instance of firebase.auth.RecaptchaVerifier 

### ISSUE THREAD

**Issue by almothafar** [DethAriel/ng-recaptcha#51]
I'm wondering how to use this component with a real use for it, currently, it is not useful for some related functions from google, like firebase.auth.RecaptchaVerifier

See this:
https://angularfirebase.com/lessons/firebase-phone-authentication-with-angular-4-tutorial/

Is it possible to return the instance of RecaptchaVerifier so I can use it to log in?

**Comment by DethAriel** [comment]
I'm afraid that this lib has nothing to do with firebase - you either use one or the other. I'm marking that as invalid.

**Comment by almothafar** [comment]
Yes, correct, it is invalid sorry :) 

I was confused, but anyway this is indeed really nothing to do with firebase, the problem when I use reCaptcha it can be passed if you really not handled the reCaptcha component in wrong way, but for firebase, I have to use the same way you render this component, to get verifier, this is why I'm confused a little, I thought it is the same component, the problem indeed Google confusion.

I think it will be nice to add a brief doc for what next, I mean to verify the token, how to do that, I got my server side (Java code) to verify the response token referring to:
https://developers.google.com/recaptcha/docs/verify
