### ISSUE TITLE
how to validate client side  captcha  with server side response

### ISSUE THREAD

**Issue by G-Deepak** [DethAriel/ng-recaptcha#53]
how to verify client side captcha with server side.

**Comment by DethAriel** [comment]
To start with, thx for reaching out! 

There's documentation on that subject [here](https://developers.google.com/recaptcha/docs/verify). 

I want to note, however, that server side token verification is not a part of this lib. If you feel that you require help with that, Google is a good place to start, followed by StackOverflow in case you get stuck. Good luck!

**Comment by dockleryxk** [comment]
Here's a rough implementation that works for me. If you follow the logic it should be pretty obvious: https://github.com/dockleryxk/easy-recaptcha-mailer
