### ISSUE TITLE
captchaRef.execute() not working in invisible captcha

### ISSUE THREAD

**Issue by sadokmtir** [DethAriel/ng-recaptcha#54]
When I tried to debug the code I found this function:

```
RecaptchaComponent.prototype.execute = function () {
        if (this.size !== 'invisible') {
            return;
        }
        if (this.widget != null) {
            this.grecaptcha.execute(this.widget);
        }
    };
```

and the problem is that `this.widget` is `undefined`.
"ng-recaptcha": "^3.0.0",
What am I missing here ?

**Comment by DethAriel** [comment]
Hello @sadokmtir ! Could you please provide more details about your environment (Angular version, typescript version, browser). If you could also reproduce the issue using this [template plunker](https://plnkr.co/edit/QjPszwnPZ4yZaCHXPOjj?p=preview), it would help greatly in tracking this issue down.

Please also note that you cannot simply use your existing recaptcha site key with invisible recaptcha - you have to configure a separate one on [reCAPTCHA admin page](https://www.google.com/recaptcha/admin).

**Comment by djejaquino** [comment]
I have the same problem using *ionic* 3.6.0

**Comment by djejaquino** [comment]
@DethAriel Nevermind. The problem was having a *script* tag loading recaptcha. Probably it was conflicting with *RecaptchaLoaderService*.

**Comment by DethAriel** [comment]
@sadokmtir could you elaborate on the problem, please? Are you loading the recaptcha yourself or relying on lib's implementation? What is the environment that you're using recaptcha in?
