### ISSUE TITLE
required: valid/invalid upside down

### ISSUE THREAD

**Issue by agomezxff** [DethAriel/ng-recaptcha#55]
It seems that the model validation is upside down as in https://dethariel.github.io/ng-recaptcha/forms.
The whole example returns valid when should be invalid, what is an issue with other form component validation

**Comment by DethAriel** [comment]
Hi!

Could you elaborate? I'm seeing correct behavior:

* Initial state:
<img width="375" alt="screen shot 2017-09-15 at 12 27 53 pm" src="https://user-images.githubusercontent.com/1497789/30500006-795e28c0-9a11-11e7-8ed1-467a8c95e05c.png">
* After user filled in the captcha:
<img width="374" alt="screen shot 2017-09-15 at 12 27 59 pm" src="https://user-images.githubusercontent.com/1497789/30500012-7ccf928c-9a11-11e7-8c30-a66e01cbee18.png">
* After captcha has been reset (either manually or via timeout):
<img width="371" alt="screen shot 2017-09-15 at 12 28 04 pm" src="https://user-images.githubusercontent.com/1497789/30500013-7e165d60-9a11-11e7-9fad-6267a981769f.png">

**Comment by agomezxff** [comment]
Ok, sorry it was my fault interpreting the hidden tag.

**Comment by DethAriel** [comment]
no worries at all, thx for submitting this anyway!
