### ISSUE TITLE
Invisible reCAPTCHA without execute

### ISSUE THREAD

**Issue by rtm** [DethAriel/ng-recaptcha#58]
Sorry if this is a support issue and shouldn't go here. I have a question about invisible reCAPTCHA.

In your docs, you state

> You will also need to invoke the "execute()" method manually. This can be done by either obtaining a reference to RecaptchaComponent via @ViewChild(), or by using inline template reference:

However, my understanding of invisible reCAPTCHA is that calling the `execute` method manually is a special case, necessary only if you want to explicitly call for the challenge to appear. It is not necessary in the normal course of events. The normal flow is that when the button associated with the reCAPTCHA is pressed, Google decides whether or it seems to be a robot, puts up the challenge if it decides it is, then calls the callback specified as the `data-callback` attribute if it believes the user is a human *or* the challenge is passed.

This is how I want things to work. I don't want to explicitly call for the challenge to appear, and I don't think I need or want to call `execute`. I tried that, and as I suspected, the challenge came up every time, which is definitely not what I want. . I just want `resolve` to be called when Google thinks things are OK. Does the component support that, and if so please help me understand how, since I am too dense to figure it out myself.

**Comment by DethAriel** [comment]
Hello, @rtm . 

This recaptcha usage would indeed be ideal. Unfortunately, this is not something that this lib supports right now - it can only be done via `execute` API at the moment. You are free to submit a pull request that will close this gap, though.

With regards to the challenge always appearing - this sounds like a totally different issue for me, it works just fine on the demo site:
![invisible-recaptcha](https://user-images.githubusercontent.com/1497789/30661960-68c3e81e-9dfa-11e7-9fdc-46e870b4628d.gif)

Note, that if you solve the captcha too many times during a short period of time - it'll start challenging you for a while. Can this be the reason you're being challenged?

**Comment by jpinxten** [comment]
@rtm 
- You can just call the execute method on ngAfterViewinit component hook.
- Or you can call the execute when a user presses the for submit, and than actually submit your form on the (resolved) callback from the re-captcha component

**Comment by kostadin-dimitrov** [comment]
I try calling execute on ngAfterViewInit but resolved function is not called. Here is the code:

@ViewChild(RecaptchaComponent) captcha: RecaptchaComponent;
.........
ngAfterViewInit() {
	this.captcha.execute();
}
.......
resolved(e) {
	console.log(e);
}

<re-captcha siteKey="SITE_KEY"
						(resolved)="resolved($event)"
						size="invisible"></re-captcha>
Could you please help me?

**Comment by DethAriel** [comment]
@kostadin-dimitrov were you able to resolve you issue? If not, could you please create a separate ticket using [this template](https://github.com/DethAriel/ng-recaptcha/issues/new)?

**Comment by jpinxten** [comment]
@kostadin-dimitrov Here is some working code: 

@ViewChild('captchaRef') captchaRef: RecaptchaComponent;

executeReCaptcha() {
    this.captchaRef.execute();
}

getReCaptchaResponse(response: string) {

}


<form [formGroup]="registrationForm" (ngSubmit)="executeReCaptcha()">
........
<re-captcha 
#captchaRef siteKey="{{recaptchaPublicKey}}"
(resolved)="getReCaptchaResponse($event)" size="invisible">
</re-captcha>
.....
</form>

**Comment by juanlet** [comment]
It works but if the login fails one time and I try a second time then a recaptcha error appears: 

"Cannot contact reCAPTCHA. Check your connection and try again."

I tried to use the reset method after a first attempt has been done doing an if on the execInvisibleRecaptcha() method with a boolean that I set if an error has ocurred to try the second time with this.captchaRef.reset() instead of execute but it doesn't work since it gives missing-input-response error on the verify captcha method on the server. My code is:

```
import { Component, OnInit, OnDestroy, ViewChild, Inject } from '@angular/core';
import { AbstractControl, FormBuilder, FormGroup, Validators, FormControl } from '@angular/forms';
import { AuthService } from 'app/auth/auth.service';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs/Subscription';



@Component({
  selector: 'app-sponsor-login',
  templateUrl: './sponsor-login.component.html',
  styleUrls: ['./sponsor-login.component.scss']
})
export class SponsorLoginComponent implements OnInit {

  loginForm: FormGroup;
  authServiceSubscription: Subscription;
  authBehaviorSubjectSubscription: Subscription;
  errorMessage ='';
  @ViewChild('captchaRef') captchaRef: any;

  constructor(private formBuilder: FormBuilder, private authService: AuthService, private router: Router) {

    this.loginForm =   new FormGroup({
          'identifier': new FormControl(null, [Validators.required]),
          'password': new FormControl(null, [Validators.required]),
          'recaptcha_reactive': new FormControl(null)
        });
   }

  ngOnInit() {


   this.authBehaviorSubjectSubscription = this
  .authService
  .sponsorIsAuthenticated
  .subscribe(isAuthenticated => {
    if (isAuthenticated) {
      this.router.navigate(['/sponsors/dashboard/overview']);
    }
  });

  }


    execInvisibleRecaptcha(){
      this.captchaRef.execute();

    }

    resolved(captchaResponse: string) {
         console.log(`Resolved captcha with response ${captchaResponse}:`);
         this.onSubmit();
     }

  onSubmit(){

    if (this.loginForm.valid) {
    this.errorMessage= "";

     this.authServiceSubscription = this.authService.loginSponsorUser(this.loginForm.value).subscribe(loginResult=>{
       console.log("Sponsor login success");
       this.authService.changeSponsorUserStatusToAuthenticated();
       this.router.navigate(['/sponsors/dashboard']);

     },(err)=>{
        console.log("There was an error login in",err.error);
        this.errorMessage = "Hubo un error en el login: "+err.error;
     });
   }
  }

  onDestroy(){
    if(this.authServiceSubscription){
    this.authServiceSubscription.unsubscribe();
    }
    if(this.authBehaviorSubjectSubscription){
      this.authBehaviorSubjectSubscription.unsubscribe();
    }
  }

}

```

```
<div class="main">
<div class="container">
  <app-error-alert *ngIf="errorMessage && errorMessage!==''" [message]="errorMessage"></app-error-alert>

  <form (ngSubmit)="execInvisibleRecaptcha()"  [formGroup]="loginForm">
    <div class="container" style="padding:2em 2em 2em 2em">
        <h3 style="margin-bottom:20px;">Iniciar sesión</h3>
  <div class="form-group">
  <input type="text" formControlName="identifier" placeholder="email or username">
</div>
<div class="form-group">
  <input type="password" formControlName="password" placeholder="password">
  <p class="small"><a [routerLink]="'/sponsors/reset-password'">¿La olvidaste?</a></p>
</div>
  <button [disabled]="!loginForm.valid" class="btn btn-primary button" style="margin-bottom:20px;">
    Login
  </button>
</div>
<div class="container-fluid footer text-center">
  <span class="small">¿No estas registrado como sponsor aun? <a class="color-primary" [routerLink]="'/sponsors/signup'">¡Crea una cuenta!</a></span>
  </div>

  <!-- invisible recaptcha -->
   <re-captcha formControlName="recaptcha_reactive" (resolved)="resolved($event)" siteKey="dsaddasadada"  size="invisible" #captchaRef="reCaptcha"></re-captcha>

</form>
</div>
</div>

{{errorMessage}}

```

So to be clear. If a user fails to login a first time, if he presses a second time then the error above is displayed. If he does it right the first time then it works. How can I reset the captcha for invisible recaptcha?

**Comment by Manipulos** [comment]
I had the same problem with "Cannot contact reCAPTCHA. Check your connection and try again."

but i fixed it by resetting on login failed

    onSubmit(){

    if (this.loginForm.valid) {
    this.errorMessage= "";

     this.authServiceSubscription = this.authService.loginSponsorUser(this.loginForm.value).subscribe(loginResult=>{
       console.log("Sponsor login success");
       this.authService.changeSponsorUserStatusToAuthenticated();
       this.router.navigate(['/sponsors/dashboard']);

     },(err)=>{
        console.log("There was an error login in",err.error);
        this.errorMessage = "Hubo un error en el login: "+err.error;
        this.captchaRef.reset();
     });
    }

**Comment by juanlet** [comment]
Thank you very much my friend. I did that the other day and it didn't work but now I retried and it works perfectly. I guess late hours are not good for coding jaja!!

**Comment by DethAriel** [comment]
I'm going to close this issue for now. The suggestion put forward by @rtm is indeed one of the ways that invisible reCAPTCHA can be integrated, but at the moment I don't see a way to do so that would be idiomatic to the Angular framework. If you're reading this, and you think otherwise - feel free to open a new issue.
