### ISSUE TITLE
OpaqueToken is deprecated and will be removed in Angular 5

### ISSUE THREAD

**Issue by SergiusSidorov** [DethAriel/ng-recaptcha#63]
Ng-recaptcha is not compiled in angular 5 project.

`
ERROR in /node_modules/ng-recaptcha/recaptcha/recaptcha-loader.service.d.ts (2,10): Module '"/node_modules/@angular/core/index"' has no exported member 'OpaqueToken'.
`

**Comment by SergiusSidorov** [comment]
I see that this change is already exist in the master branch. Please tell me when will the version with these changes?

**Comment by DethAriel** [comment]
Fixed in v3.0.1
