### ISSUE TITLE
ERROR in production build

### ISSUE THREAD

**Issue by lanzosuarez** [DethAriel/ng-recaptcha#65]
Got this error with ng build --aot --prod

ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 29:55 in the original .ts file), resolving symbol RecaptchaLoaderService

 "@angular/animations": "^4.1.3",
    "@angular/common": "^4.0.2",
    "@angular/compiler": "^4.0.2",
    "@angular/core": "^4.0.2",
    "@angular/forms": "^4.0.2",
    "@angular/http": "^4.0.2",
    "@angular/platform-browser": "^4.0.2",
    "@angular/platform-browser-dynamic": "^4.0.2",
    "@angular/router": "^4.0.2"
}

"devDependencies": {
    "@angular/cli": "^1.0.1",
    "@angular/compiler-cli": "^4.0.2",
    "@types/jasmine": "2.5.38",
    "@types/jquery": "^2.0.46",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }

**Comment by deathbearbrown** [comment]
I'm also getting this error:
```ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 29:55 in the original .ts file), resolving symbol RecaptchaLoaderService in /Users/deathbear/CODE/SPLICE/marketing/node_modules/ng-recaptcha/recaptcha/recaptcha-loader.service.d.ts```

**Comment by deathbearbrown** [comment]
I will probably have a PR for this tomorrow.
