### ISSUE TITLE
ReCAPTCHA couldn't find user-provided function when I visit the page using router

### ISSUE THREAD

**Issue by almothafar** [DethAriel/ng-recaptcha#66]
I have Angular 4.4.4 app, using https://github.com/AngularClass/angular-starter 
I have Sign-Up page in different module, when I go from home page to Sign-up I get the following error:
```
recaptcha__en.js:376 ReCAPTCHA couldn't find user-provided function: __rcb206869
```

But if I refresh the page it is working without any problem.

```
<form (ngSubmit)="signUp()" [formGroup]="userForm">
            <fieldset>
              <label for="firstName">First Name</label>
              <input id="firstName" type="text" [(ngModel)]="user.firstName" formControlName="firstName" required/>
            </fieldset>

            <fieldset>
              <label for="lastName">Last Name</label>
              <input id="lastName" type="text" [(ngModel)]="user.lastName" formControlName="lastName" required/>
            </fieldset>

            <fieldset>
              <label for="email">Email Address</label>
              <input id="email" type="email" [(ngModel)]="user.email" formControlName="email" required/>
              <label class='validation-message' *ngIf="userForm.controls.email.hasError('email')">
                Email address is invalid.
              </label>
            </fieldset>

            <fieldset>
              <label for="password">Password</label>
              <input id="password" type="password" [(ngModel)]="password" formControlName="password" required/>
            </fieldset>

            <fieldset>
              <re-captcha (resolved)="resolvedCaptcha($event)" [siteKey]="SITE_ID"></re-captcha>
            </fieldset>

            <fieldset class="form-actions">
              <button type="submit" class="button primary twelve" [disabled]="!userForm.valid || !captchaValid" [uiBlockButton]="processingRequest">Sign Up</button>
            </fieldset>

            <fieldset class="form-actions">
              <a (click)="cancel()">Cancel</a>
            </fieldset>
          </form>
```

Sign up module:

```
export const routes: Routes = [
  {
    path: '', component: LoginMainComponent,
    children: [
      {path: '/sign-up', component: SignUpPageComponent}
    ]
  }
];

@NgModule({
  declarations: [
    SignUpPageComponent
  ],
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RecaptchaModule.forRoot(),
    RouterModule.forChild(routes)
  ],
})
export class LoginMainModule {
  public static routes = routes;
}


```

app module:
```

export const ROUTES: Routes = [
  {path: '', loadChildren: '../pages/+login#LoginMainModule'},
]

@NgModule({
  bootstrap: [AppComponent],
  declarations: [
    AppComponent
  ],
  imports: [ // import Angular's modules
    AngularFireModule.initializeApp(ENV_FIREBASE_CONFIG),
    NgPipesModule,
    WidgetsModule,
    CustomFormsModule,
    CustomModalModule,
    BrowserAnimationsModule,
    TelecomsServicesModule,
    RouterModule.forRoot(ROUTES, {preloadingStrategy: PreloadAllModules})
  ],
  providers: [ // expose our Services and Providers into Angular's dependency injection
    ENV_PROVIDERS,
    APP_PROVIDERS
  ]
})
export class AppModule {}
```

Lets say main page got link like:

`<a [routerLink]=" ['/sign-up']" routerLinkActive="active">Sign-Up</a>`

The error shown, the re-captcha not working.

**Comment by almothafar** [comment]
Just for follow up: 

I rendered reCaptcha using Google API directly and I was able to make it work without any issues:

```
            <fieldset>
              <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit" async defer></script>
              <div #captchaRef2></div>
            </fieldset>
```

Inside component.ts file:

```
@ViewChild('captchaRef2') captchaRef2: ElementRef;
private _reCaptchaId: number;

ngAfterViewInit() {
    const grecaptcha = (window as any).grecaptcha;
    if (grecaptcha) {
      this._reCaptchaId = grecaptcha.render(this.captchaRef2.nativeElement, {
        'sitekey': this.SITE_ID,
        'callback': (resonse) => this.resolvedCaptcha(resonse),
        'expired-callback': () => grecaptcha2.reset(this._reCaptchaId)
      });
    }
  }

```

And worked like a charm.

So, for now, I removed this component and doing it manually.

**Comment by DethAriel** [comment]
Thx for submitting this, @almothafar !

The error looks a bit strange to me:

> recaptcha__en.js:376 ReCAPTCHA couldn't find user-provided function: **__rcb206869**

especially the emphasized part. As seen [here](https://github.com/DethAriel/ng-recaptcha/blob/master/recaptcha/recaptcha-loader.service.ts#L50), the name of the callback that lib provides is `ng2recaptchaloaded`, and is non-modifyable. Hence I'm not quite sure how to reproduce this issue

**Comment by almothafar** [comment]
I'm not sure what happened, but the number '__rcb206869'  is just random like I see this issue with '__rcb860183' right now, but as told you if I were in another page and visited the page, the component is broken, but if I refresh the page it is working, and even if I went out and came later it is will still be working correctly.

I created my own component, in a simple way as I did above in my 2nd comment, it is working all the way and in all scenarios. 

My project based on the start that I mentioned in the OP.

**Comment by DethAriel** [comment]
@almothafar are you able to provide more information on this issue, or has it been resolved on your end?

**Comment by almothafar** [comment]
@DethAriel  actually nothing new, I have no more using this dependency, but I got something to handle this case by reading the issue and try to render again after 1 second until I get the element.

**Comment by DethAriel** [comment]
@almothafar you can also try and see whether v3.0.3 fixed the original issue, hopefully it did

**Comment by kaiz123** [comment]
Define your functions as var and not const or let. If that doesnt work then use window.callback=function(){}
