### ISSUE TITLE
Getting error after adding import { RecaptchaModule } in app.module.ts

### ISSUE THREAD

**Issue by Shariaty** [DethAriel/ng-recaptcha#70]
I am getting this error in chrome console.
is this component can be used with angular 4.3.4. if it is would you please help me to understand what is the problem !?

ERROR
GET http://localhost:3000/ng-recaptcha/ 404 (Not Found)  zone.js:2744 . 
(index):30 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/ng-recaptcha

**Comment by DethAriel** [comment]
Hi, @Shariaty ! Could you please elaborate as to what this URL (http://localhost:3000/ng-recaptcha/) is - is it your app, or something else?

**Comment by Shariaty** [comment]
@DethAriel  Thanx for you reply. I figure it out.
 After i add 'ng-recaptcha' : 'node_modules/ng-recaptcha' to my systemjs.config.js  in the map array the error goes away.

**Comment by DethAriel** [comment]
@Shariaty thx for following-up, I'm glad your issue was resolved!
