### ISSUE TITLE
ng2-recaptcha is not working in angular 5 as OpaqueToken got deprecated from @angular/core in version 5. Any solution for the same?

### ISSUE THREAD

**Issue by drakshit** [DethAriel/ng-recaptcha#72]
### Summary

I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [x] question / support request
- [ ] other

**Comment by pczora** [comment]
I had the same problem until I updated to version 3.0.2. [This commit](https://github.com/DethAriel/ng-recaptcha/commit/2b7db9b24ce133e6a4a9cefd8e1e8c0178cee69b) switches from OpaqueToken to InjectionToken.

**Comment by drakshit** [comment]
Hi pczora
Thanks for your reply, I had to replace the package ng2-recaptcha to ng-recaptcha 3.0.2 in order to work.
