### ISSUE TITLE
Expired callback

### ISSUE THREAD

**Issue by gtzinos** [DethAriel/ng-recaptcha#73]
Hi guys,

Thanks for your great library. I am searching to find a workaround to check if the recaptcha is verified. I found only the resolve function but it doesn't fire again when the verification expired. Any workaround ?

**Comment by DethAriel** [comment]
Hi, @gtzinos ! The `resolved` callback should fire with `null` value when the recaptcha expires, is that not the behavior you observe?

**Comment by gtzinos** [comment]
It works great, sorry.

**Comment by DethAriel** [comment]
@gtzinos no worries, thx for triaging this!

**Comment by sasanazizi** [comment]
https://github.com/DethAriel/ng-recaptcha#events
