### ISSUE TITLE
Error when trying to load the component the second time 

### ISSUE THREAD

**Issue by PavoneM** [DethAriel/ng-recaptcha#78]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description
I'm using Angular 2 with semantic UI, ng-recaptcha in version ^3.0.2.
When working with a modal, the first time I open the popup the component is rendered as it should be. 
The second time I open the modal I get this error : ReCAPTCHA placeholder element must be an element or id
![image](https://user-images.githubusercontent.com/9719078/34341742-4cd63a7c-e99e-11e7-891c-6ea53fced0a6.png)

### Personal investigation
In debug mode I found in the constructor of RecaptchaComponent it increment the id each time on line 11 "ngrecaptcha-" + nextId++;

Lib versions:

* ng-recaptcha: ___3.0.2
* Angular: ___4.4.5
* Typescript (`tsc --version`): ___2.5.3

**Comment by DethAriel** [comment]
Should have been fixed by #77
