### ISSUE TITLE
Error after use it

### ISSUE THREAD

**Issue by MansoorJafari** [DethAriel/ng-recaptcha#81]
Hi
after I'm using this library my captcha give me this error

ERROR for site owner: Invalid site key

I'm using for domain localhost:5000

please help.

**Comment by macelocosta** [comment]
Same problem here.

**Comment by DethAriel** [comment]
@MansoorJafari @macelocosta thx for your feedback! This does not look like an issue in the library code, but more like a general reCAPTCHA usage question. I would encourage you to check out [reCAPTCHA FAQ](https://developers.google.com/recaptcha/docs/faq), and [this section](https://developers.google.com/recaptcha/docs/faq#recently-my-recaptcha-widget-started-displaying-invalid-site-key-whats-happening) in particular.

If that doesn't resolve your problem and you believe that `ng-recaptcha` lib is responsible, feel free to submit a [new issue](https://github.com/DethAriel/ng-recaptcha/issues/new) following the given issue template.

Thank you!
