### ISSUE TITLE
Getting error on server - ERROR for site owner: Invalid domain for site key

### ISSUE THREAD

**Issue by smartHasmukh** [DethAriel/ng-recaptcha#83]
### Summary
Working on local server but getting error on live server
 
### Demo

> HTML CODE

> > 
 `<re-captcha (resolved)="resolved($event)" siteKey="6LcOuyYTAAAAAHTjFuqhA52fmfJ_j5iFk5PsfXaU"></re-captcha>`
 

> TYPESCRIPT CODE

 
 `resolved(captchaResponse: string) {
     console.log(`Resolved captcha with response ${captchaResponse}:`);
   }`

### Project Config

* ng-recaptcha: 3.0.3
* Angular: 5
* Angular-cli: 1.6.5
* Typescript (`tsc --version`): 2.5.3

**Comment by DethAriel** [comment]
Hello, @smartHasmukh, and thank you for reaching out! I must admit, though, that this error does not seem to be related to the functionality of this library, but rather to the reCAPTCHA configuration. I suggest you look this error up in some search engine, you can start with [this StackOverflow question](https://stackoverflow.com/questions/30735694/recaptcha-error-invalid-domain-for-site-key), for example.
