### ISSUE TITLE
Cannot read property 'closest' of null

### ISSUE THREAD

**Issue by victorfreitas** [DethAriel/ng-recaptcha#85]
### Summary

I'm submitting a: 

- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description

You are experiencing this error in the console [Uncaught TypeError: Cannot read property 'closest' of null]

### Demo

- [ ] See the example console below, It's the same problem I have in my project.

https://dethariel.github.io/ng-recaptcha/invisible

Lib versions:

* ng-recaptcha: 3.0.3
* Angular: 5.2.3
* Typescript (`tsc --version`): 2.6.2

**Comment by DethAriel** [comment]
Hello, @victorfreitas, thx for submitting this! Could you please elaborate on what browser does this happen? I checked latest Chrome/FF/Safari and did not see this
