### ISSUE TITLE
has no exported member 'OpaqueToken'

### ISSUE THREAD

**Issue by shubhrajodiya** [DethAriel/ng-recaptcha#86]
ERROR in node_modules/ng2-recaptcha/recaptcha/recaptcha-loader.service.d.ts(2,10): error TS2305: Module '"E:/tecqnihomeapp/angular-src/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

How can I resolve this Error?

"angular/core": "^5.0.0"
"angular/cli": "1.6.0"

**Comment by pratyaydas** [comment]
How do you solve this problem?I am facing same issue.

**Comment by shubhrajodiya** [comment]
I actually unable to recall the exact solution but I am having a backup of the app which I developed if you want I can share it.

You can figure it out by yourself.
