### ISSUE TITLE
Having problems with RecaptchaModule

### ISSUE THREAD

**Issue by keybabss** [DethAriel/ng-recaptcha#87]
### Summary

- [ ] bug report
- [ ] feature request
- [x] question / support request
- [ ] other

### File Structure

```
├── + lib
|   ├──  + components  
|   |    ├── + my-captcha  // MyCaptcha Module
|   |    |   ├── + src 
|   |    |   |    ├── my-captcha.component.ts // MyCaptcha component
|   |    |   └── module.ts // this is where we use the RecaptchaModule
|   |    └── index.ts // export MyCaptcha
|   └── + css
|   └── + directives
├── + node_modules // installed ng-recaptcha 3.0.3 and compiler-cli 1.6.5
├── + publish-config
|   ├── tsconfig.compile.json // typescript config - compiler json file
|   └── tsconfig.json // typescript config - json file
├── + sandbox
|   └── module.ts // Sandbox module 
```

### File Contents

1.) publish-config/tsconfig.compile.json

```

{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "lib": [
      "es2015",
      "dom"
    ],
    /* Specify library files to be included in the compilation:  */
    "declaration": true,
    "sourceMap": true,
    "outDir": "dist",
    "rootDir": "../lib/",
    "skipLibCheck": true,
    /* Strict Type-Checking Options */
    "strict": true,
    "noImplicitAny": true, 
    "strictNullChecks": true,
    "stripInternal": true,
    /* Module Resolution Options */
    "moduleResolution": "node", 
    "baseUrl": "./", 
    "paths": {
      "@angular/core": [
        "node_modules/@angular/core/*"
      ]
    },
    /* Source Map Options */
    "inlineSources": true,
    /* Experimental Options */
    "experimentalDecorators": true 
  },
  "files": [
    "../lib/components/index.ts"
  ],
  "angularCompilerOptions": {
    "strictMetadataEmit": false,
    "genDir": "aot-dist"
  }
}
```

2.) lib/components/index.ts

`export * from './my-captcha/module';`

3.) lib/component/my-captcha/module.ts

```
import {NgModule} from '@angular/core';
import {RecaptchaModule} from "ng-recaptcha";
import {MyCaptcha} from "./src/my-captcha.component";
import {FormsModule, ReactiveFormsModule} from "@angular/forms";
import {CommonModule} from "@angular/common";
import {MyCaptchaResponseValidatorService} from "./src/my-captcha.service";
import {MyCaptchaResponseValidatorServiceImpl} from "./src/my-captcha.service.impl";

export const MY_CAPTCHA_DECLARATIONS = [MyCaptcha];

@NgModule({
    imports: [CommonModule, FormsModule, ReactiveFormsModule, RecaptchaModule.forRoot()],
    declarations: [
        MY_CAPTCHA_DECLARATIONS
    ],
    exports: [
        MyCaptcha
    ],
    providers: [{provide: MyCaptchaResponseValidatorService, useClass: MyCaptchaResponseValidatorServiceImpl}]
})
export class MyCaptchaModule {
}
```

### Description

From the root directory, I run this command (via terminal):
_./node_modules/.bin/ngc -p ./publish-config/tsconfig.compile.json_ 

### Current Behaviour 

1.) If did not add the _RecaptchaComponent_ in the MyCaptchaModule (under declarations), it will show this compiler error... 

_: Cannot determine the module for class RecaptchaComponent in /node_modules/ng-recaptcha/recaptcha/recaptcha.component.d.ts! Add RecaptchaComponent to the NgModule to fix it._

2.) If I did follow the compiler error by adding the _RecaptchaComponent_ in the MyCaptchaModule, it shows this error...

_: Type RecaptchaComponent in ./node_modules/ng-recaptcha/recaptcha/recaptcha.component.d.ts is part of the declarations of 2 modules: RecaptchaCommonModule in ./node_modules/ng-recaptcha/recaptcha/recaptcha-common.module.d.ts and MyCaptchaModule in ./lib/components/my-captcha/module.ts! Please consider moving RecaptchaComponent in ./node_modules/ng-recaptcha/recaptcha/recaptcha.component.d.ts to a higher module that imports RecaptchaCommonModule in ./node_modules/ng-recaptcha/recaptcha/recaptcha-common.module.d.ts and MyCaptchaModule in ./lib/components/my-captcha/module.ts. You can also create a new NgModule that exports and includes RecaptchaComponent in ./node_modules/ng-recaptcha/recaptcha/recaptcha.component.d.ts then import that NgModule in RecaptchaCommonModule in ./node_modules/ng-recaptcha/recaptcha/recaptcha-common.module.d.ts and MyCaptchaModule in ./lib/components/my-captcha/module.ts._

### Expected Behaviour

It will create a **dist** folder containing javascript code inside the _publish-config_ folder

Library versions:

* ng-recaptcha: 3.0.3
* Angular: 5.2.3
* Typescript (`tsc --version`): 2.1.5

**Comment by DethAriel** [comment]
Hello! Could you please elaborate on how does your `my-captcha.component.ts` look like?

Another thing - it doesn't look like `MyCaptchaModule` is the root module of your application. If so, you should remove the `forRoot()` function call, and move it to the root module of your app.

**Comment by DethAriel** [comment]
@keybabss were you able to resolve your issue?

**Comment by DethAriel** [comment]
Closing this issue for now due to lack of actionable information. @keybabss feel free to add details and reopen if the issue hasn't been resolved yet, or you can share your findings on issue resolution.
Thanks!

**Comment by FlacosFlace** [comment]
I have exactly the same problem. 
**ERROR**: 
Cannot determine the module for class RecaptchaComponent in /home/fladr/PhpstormProjects/Angular-nil/node_modules/ng-recaptcha/recaptcha/recaptcha.component.d.ts! Add RecaptchaComponent to the NgModule to fix it.

import {RecaptchaFormsModule} from 'ng-recaptcha/forms';
import {RECAPTCHA_SETTINGS, RecaptchaModule, RecaptchaSettings} from 'ng-recaptcha';

In my module:
@NgModule({
    imports: [
        RecaptchaFormsModule,
        RecaptchaModule.forRoot(),
    ],
    declarations: [
         FormCaptchaComponent
    ],
    providers: [
        {
            provide: RECAPTCHA_SETTINGS,
            useValue: {
                siteKey: '*********************************',
            } as RecaptchaSettings,
        },
    ],
})


And my FormCaptchaComponent view:

        <div    [style.display]="config.display ? 'inline-block' : 'none'"
                class="dynamic-field form-captcha"
                [formGroup]="group">
                <re-captcha
                        [formControlName]="config.name">
                </re-captcha>
        </div>

I'm trying comand: ng buil form --prod.
