### ISSUE TITLE
Using captchaRef.execute() without size invisible

### ISSUE THREAD

**Issue by heltonalves99** [DethAriel/ng-recaptcha#88]
### Summary

I'm submitting a:
- [ ] bug report
- [ ] feature request
- [ X ] question / support request
- [ ] other

### Description
Hi guys, how are you ?
I'm trying to use captchaRef.execute() without size invisible.
is there any way ?

Another question:
I'm trying to check recaptcha by angular protractor, making E2E tests.
the recaptcha is checked normally, but the resolved callback does not run.
anyone has used protractor to check recaptcha?

ex code:
```
    browser.ignoreSynchronization = true;
    browser.switchTo().frame(element(by.css('recaptcha iframe')).getWebElement())
    .then(() => {
      let checkmark = browser.findElement(by.className('recaptcha-checkbox-checkmark'));
      // first hover the checkbox
      browser.actions().mouseMove(checkmark).perform();
      browser.sleep(500);
      checkmark.click();
    })
    .then(() => {
      browser.ignoreSynchronization = false;
      browser.switchTo().defaultContent();
    });
```

Lib versions:
* ng-recaptcha: 1.7.0
* Angular: 4.4.6

**Comment by DethAriel** [comment]
Hello, @heltonalves99 ! The `execute()` function is only part of invisible reCAPTCHA API, and cannot be performed on non-invisible elements - it's simply a noop as you can see [here](https://github.com/DethAriel/ng-recaptcha/blob/v1.7.0/recaptcha/recaptcha.component.ts#L70).

Wrt protractor tests - I'm assuming you're using the [proper test keys](https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha-v2-what-should-i-do), right? The code you use looks good to me.

**Comment by heltonalves99** [comment]
Thanks @DethAriel.
I saw about execute() works only with invisible. But what do you think about this feature ? execute() works anyway, with or without invisible?

**Comment by DethAriel** [comment]
@heltonalves99 Unfortunately there is no hook in reCAPTCHA API that we could utilize to deliver such a feature :(. Essentially, what I believe they're thinking is, "If you want to resolve the thing programmatically - don't even bother with showing the checkbox to the user".
