### ISSUE TITLE
How to Resize ng-recaptch in my forms?

### ISSUE THREAD

**Issue by zshahab91** [DethAriel/ng-recaptcha#89]
### Summary

I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [x] question / support request
- [ ] other

**Comment by DethAriel** [comment]
Hello, @zshahab91 ! Did you consider using the `transform` hack from [StackOverflow](http://stackoverflow.com/questions/27691411/change-new-google-recaptcha-width) or [this blog](https://geekgoddess.com/how-to-resize-the-google-nocaptcha-recaptcha/)? I suppose that should cover the resizing part of it, but please let me know if you have additional questions after that!
