### ISSUE TITLE
ERROR Error: No value accessor for form control with name: 'recaptchaReactive'

### ISSUE THREAD

**Issue by Kailash0593** [DethAriel/ng-recaptcha#92]
I am using the relative form approach ( Angular 5.2 ) : 
@Component({
  selector: 'my-reactive-form',
  template: `
    <form [formGroup]="reactiveForm">
      <re-captcha formControlName="recaptchaReactive"></re-captcha>
      <button [disabled]="reactiveForm.invalid">Submit</button>
    </form>
  `,
}) export class MyReactiveForm {
  reactiveForm: FormGroup;

  ngOnInit() {
    this.reactiveForm = new FormGroup({
      recaptchaReactive: new FormControl(null, Validators.required)
    });
  }
Error : 
ERROR Error: No value accessor for form control with name: 'recaptchaReactive'

**Comment by osman2109** [comment]
Try it with importing the RecaptchaFormsModule in your module.

**Comment by Kailash0593** [comment]
@osman2109 thank you it worked!!

**Comment by Jayeshneema1** [comment]
But is showing the same error "Error: No value accessor for form control with name: 'recaptchaReactive'" when I Run "ng test --browsers Chrome --cc"

**Comment by cfood** [comment]
> But it is showing the same error "**Error: No value accessor for form control with name: 'recaptchaReactive'**" when I Run "ng test --browsers Chrome --cc"

I get the same error in the Jasmine tests. RecaptchaFormsModule is imported but no luck. 

Any ideas anyone?

**Comment by DethAriel** [comment]
@Jayeshneema1 @cfood do you still see this issue? If so, could you provide code sample that results in  this error?
