### ISSUE TITLE
No value accessor for form control with unspecified name attribute

### ISSUE THREAD

**Issue by ildar-icoosoft** [DethAriel/ng-recaptcha#94]
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description
I'm trying to use re-captcha with [angular reactive forms](https://angular.io/guide/reactive-forms) and I'm getting error: No value accessor for form control with unspecified name attribute

Here is my form template:

```
<form [formGroup]="group" novalidate>
    <ion-input [formControl]="email"></ion-input>
    <re-captcha [formControl]="recaptcha"
              siteKey="6Ld9IVQUAAAAAMhmrmrq6-tguCmHxt7EKvGTo7fg">              
            </re-captcha>
</form>
```

Component:
```
this.email = new FormControl('', Validators.compose([Validators.required, Validators.email]));
this.recaptcha = new FormControl(null, Validators.compose([Validators.required]));

this.group = this.formBuilder.group({
  email: this.email,
  recaptcha: this.recaptcha
});
```

In this example email form control works fine, but recaptcha does not work

**Comment by DethAriel** [comment]
Hi, @ildar-icoosoft !

A per ["Working with `@angular/forms`" section](https://github.com/DethAriel/ng-recaptcha#working-with-angularforms), did you import the `RecaptchaFormsModule` and added it to your AppModule?

**Comment by DethAriel** [comment]
@ildar-icoosoft were you able to resolve your issue?

**Comment by ildar-icoosoft** [comment]
@DethAriel Thank you very much, it works for me
