### ISSUE TITLE
How can i get custom size of recaptcha element

### ISSUE THREAD

**Issue by bmp93** [DethAriel/ng-recaptcha#97]
### Summary

I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [x] question / support request
- [ ] other

**Comment by DethAriel** [comment]
Thx for reaching out, @bmp93 ! Before I am able to assist you, could you please elaborate a bit more on what you're trying to achieve and what are the obstacles that you encountered on your path?

**Comment by DethAriel** [comment]
This can be achieved via a wrapping `<div>` that has a `transform` property, see [this StackOverflow answer](http://stackoverflow.com/questions/27691411/change-new-google-recaptcha-width) or [this blog](https://geekgoddess.com/how-to-resize-the-google-nocaptcha-recaptcha/).
