### ISSUE TITLE
Error in console while loading captcha

### ISSUE THREAD

**Issue by bmp93** [DethAriel/ng-recaptcha#98]
### Summary

I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [X] question / support request
- [ ] other

### Description
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'report-sample' 'nonce-yjKFSZ*********lo4' 'unsafe-inline' 'strict-dynamic' https: http: 'unsafe-eval'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

**Comment by DethAriel** [comment]
Hello, @bmp93 ! 

There is an [FAQ](https://developers.google.com/recaptcha/docs/faq#im-using-content-security-policy-csp-on-my-website-how-can-i-configure-it-to-work-with-recaptcha) section in reCAPTCHA docs around Content Security Policy.

While their recommended approach of using nonces is not currently supported by the lib (I've raised #100 to tack that), you can still configure your server to correctly load reCAPTCHA scripts
